## BACK LIGHT
- alias: message_back_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/back_light'
  action:
  - service: script.message_back_light
