## BACK LIGHT
- alias: message_back_light'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/back_light'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/back_light'
  action:
  - service: script.message_back_light

- alias: 'message_back_light_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_hall_on'
  action:
  - service: script.message_back_light_hall

- alias: 'message_back_light_bedroom_1'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_bedroom_1_on'
  action:
  - service: script.message_back_light_bedroom_1

- alias: 'message_back_light_bedroom_2'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_bedroom_2_on'
  action:
  - service: script.message_back_light_bedroom_2

- alias: 'message_back_light_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_living_on'
  action:
  - service: script.message_back_light_living
