## CLOUD
- alias: message_cloud'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/climat'
  action:
  - service: script.message_cloud
