## CLOUD
- alias: message_cloud'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/cloud'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/cloud'
  action:
  - service: script.message_cloud
