## CURTAIN
- alias: message_curtain'
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/curtain'
  action:
  - service: script.message_curtain
