## CURTAIN
- alias: message_curtain'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_curtain'
  action:
  - service: script.message_curtain
