## CURTAINS
- alias: message_dehumidifier'
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/dehumidifier'
  action:
  - service: script.message_dehumidifier
