## DEHUMIDIFIER
- alias: message_dehumidifier'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_dehumidifier'
  action:
  - service: script.message_dehumidifier
