## DOORS
- alias: message_door'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/door'
  action:
  - service: script.message_door

- alias: 'message_door_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_hall_open'
  action:
  - service: script.message_door_hall

- alias: 'message_door_balcony'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_balcony_open'
  action:
  - service: script.message_door_balcony
