## DOORS
- alias: message_door'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/door'
  action:
  - service: script.message_door

- alias: 'message_door_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_hall_open'
  action:
  - service: script.message_door_hall

- alias: 'message_door_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_bedroom_open'
  action:
  - service: script.message_door_bedroom

- alias: 'message_door_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_living_open'
  action:
  - service: script.message_door_living

- alias: 'message_door_balcony'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_balcony_open'
  action:
  - service: script.message_door_balcony
