## FOUNTAINS
- alias: message_fountain'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_fountain'
  action:
  - service: script.message_fountain
