## HUMIDIFIER
- alias: message_humidifier'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_humidifier'
  action:
  - service: script.message_humidifier

- alias: message_humidifier_empty'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/humidifier_empty'
  action:
  - service: script.message_humidifier_empty

- alias: 'message_humidifier_empty_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_hall_empty_boolean'
    to: 'on'
  action:
  - service: script.message_humidifier_empty_hall

- alias: 'message_humidifier_empty_bedroom'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_bedroom_empty_boolean'
    to: 'on'
  action:
  - service: script.message_humidifier_empty_bedroom

- alias: 'message_humidifier_empty_living'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_living_empty_boolean'
    to: 'on'
  action:
  - service: script.message_humidifier_empty_living
