## HUMIDIFIER
- alias: message_humidifier'
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/humidifier'
  action:
  - service: script.message_humidifier

- alias: message_humidifier_empty'
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/humidifier_empty'
  action:
  - service: script.message_humidifier_empty

- alias: 'message_humidifier_empty_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_hall_empty_boolean'
  action:
  - service: script.message_humidifier_empty_hall

- alias: 'message_humidifier_empty_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_bedroom_empty_boolean'
  action:
  - service: script.message_humidifier_empty_bedroom

- alias: 'message_humidifier_empty_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_living_empty_boolean'
  action:
  - service: script.message_humidifier_empty_living
