## HUMIDITY
- alias: message_humidity'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/humidity'
  action:
  - service: script.message_humidity

- alias: 'message_humidity_bath'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidity_bath_hight'
  action:
  - service: script.message_humidity_bath

- alias: 'message_humidity_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidity_hall_low'
  action:
  - service: script.message_humidity_hall

- alias: 'message_humidity_bedroom'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidity_bedroom_low'
  action:
  - service: script.message_humidity_bedroom

- alias: 'message_humidity_living'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidity_living_low'
  action:
  - service: script.message_humidity_living
