## HUMIDITY
- alias: message_humidity'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/humidity'
  action:
  - service: script.message_humidity
