## NAVIGATION LIVING
- alias: message_navigation_living'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living'
  action:
  - service: script.message_navigation_living

## NAVIGATION LIVING CURATAIN
- alias: message_navigation_living_curtain'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_curtain'
  action:
  - service: script.message_navigation_living_curtain

## NAVIGATION LIVING CLIMAT
- alias: message_navigation_living_climat'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_climat'
  action:
  - service: script.message_navigation_living_climat

## NAVIGATION LIVING SWITCH
- alias: message_navigation_living_switch'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_switch'
  action:
  - service: script.message_navigation_living_switch

## NAVIGATION LIVING LIGHT
- alias: message_navigation_living_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_light'
  action:
  - service: script.message_navigation_living_light

## NAVIGATION LIVING TOP LIGHT
- alias: message_navigation_living_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_top_light'
  action:
  - service: script.message_navigation_living_top_light

## MESSAGE LIVING HUMIDIFIER EMPTY
- alias: 'message_empty_humidifier_living'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_living_empty_boolean'
    from: 'off'
    to: 'on'
  action:
  - service: script.message_empty_humidifier_living
