## NAVIGATION REMOVE
- alias: message_navigation_remove'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
  action:
  - service: script.message_navigation_remove
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'

## NAVIGATION HOME
- alias: message_navigation_home'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/home'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/home'
  action:
  - service: script.message_navigation_home

## NAVIGATION DETAILS CLIMAT
- alias: message_navigation_climat'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/climat'
  action:
  - service: script.message_navigation_climat

## NAVIGATION DETAILS TOP LIGHT
- alias: message_navigation_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/top_light'
  action:
  - service: script.message_navigation_top_light
