## NAVIGATION HOME
- alias: message_navigation_home'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/home'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/home'
  action:
  - service: script.message_navigation_home

## NAVIGATION DETAILS
- alias: message_navigation_details'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details'
  action:
  - service: script.message_navigation_details

## NAVIGATION DETAILS TOP LIGHT
- alias: message_navigation_device_top_light'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light'
  action:
  - service: script.message_navigation_device_top_light

## NAVIGATION MANAGE
- alias: message_navigation_manage'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/manage'
  action:
  - service: script.message_navigation_manage

## NAVIGATION MANAGE TOP LIGHT
- alias: message_navigation_manage_top_light'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/manage_top_light'
  action:
  - service: script.message_navigation_manage_top_light

## NAVIGATION REMOVE
- alias: message_navigation_remove'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/hide_menu'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/home'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/manage'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/manage_top_light'
  action:
  - service: script.delete_telegramm_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
