## NAVIGATION REMOVE
- alias: message_navigation_remove'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
  action:
  - service: script.message_navigation_remove
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'

## NAVIGATION HOME
- alias: message_navigation_home'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/home'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/home'
  action:
  - service: script.message_navigation_home

## NAVIGATION CLIMAT
- alias: message_navigation_climat'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/climat'
  action:
  - service: script.message_navigation_climat

## NAVIGATION SECURITY
- alias: message_navigation_security'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/security'
  action:
  - service: script.message_navigation_security

## NAVIGATION LIGHT
- alias: message_navigation_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/light'
  action:
  - service: script.message_navigation_light

## NAVIGATION RGB LIGHT
- alias: message_navigation_rgb_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/rgb_light'
  action:
  - service: script.message_navigation_rgb_light

## NAVIGATION TOP LIGHT
- alias: message_navigation_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/top_light'
  action:
  - service: script.message_navigation_top_light

## NAVIGATION BACK LIGHT
- alias: message_navigation_back_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/back_light'
  action:
  - service: script.message_navigation_back_light

## NAVIGATION NIGHT LIGHT
- alias: message_navigation_night_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/night_light'
  action:
  - service: script.message_navigation_night_light
