## NAVIGATION REMOVE
- alias: message_navigation_remove'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
  action:
  - service: script.message_navigation_remove
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'

## NAVIGATION HOME
- alias: message_navigation_home'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/home'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/home'
  action:
  - service: script.message_navigation_home

## NAVIGATION KITCHEN
- alias: message_navigation_kitchen'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/kitchen'
  action:
  - service: script.message_navigation_kitchen

## NAVIGATION KITCHEN TOP LIGHT
- alias: message_navigation_kitchen_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/kitchen_top_light'
  action:
  - service: script.message_navigation_kitchen_top_light

## NAVIGATION KITCHEN SWITCH
- alias: message_navigation_kitchen_switch'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/kitchen_switch'
  action:
  - service: script.message_navigation_kitchen_switch

## NAVIGATION BATH
- alias: message_navigation_bath'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/bath'
  action:
  - service: script.message_navigation_bath

## NAVIGATION TOILET
- alias: message_navigation_toilet'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/toilet'
  action:
  - service: script.message_navigation_toilet

## NAVIGATION HALL
- alias: message_navigation_hall'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/hall'
  action:
  - service: script.message_navigation_hall

## NAVIGATION HALL TOP LIGHT
- alias: message_navigation_hall_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/hall_top_light'
  action:
  - service: script.message_navigation_hall_top_light

## NAVIGATION BEDROOM
- alias: message_navigation_bedroom'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/bedroom'
  action:
  - service: script.message_navigation_bedroom

## NAVIGATION BEDROOM TOP LIGHT
- alias: message_navigation_bedroom_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/bedroom_top_light'
  action:
  - service: script.message_navigation_bedroom_top_light

## NAVIGATION BEDROOM SWITCH
- alias: message_navigation_bedroom_switch'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/bedroom_switch'
  action:
  - service: script.message_navigation_bedroom_switch

## NAVIGATION LIVING
- alias: message_navigation_living'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living'
  action:
  - service: script.message_navigation_living

## NAVIGATION BALCONY
- alias: message_navigation_balcony'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony'
  action:
  - service: script.message_navigation_balcony

## NAVIGATION LIVING TOP LIGHT
- alias: message_navigation_living_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_top_light'
  action:
  - service: script.message_navigation_living_top_light

## NAVIGATION LIVING SWITCH
- alias: message_navigation_living_switch'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/living_switch'
  action:
  - service: script.message_navigation_living_switch
