## NETWORK
- alias: message_network'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/network'
  action:
  - service: script.message_network
