## NIGHT MODE
- alias: message_night_mode'
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/night_mode'
  action:
  - service: script.message_night_mode
