## NIGHT LIGHT
- alias: message_night_light'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_night_light'
  action:
  - service: script.message_night_light
