## NIGHT MODE
- alias: message_night_mode'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_night_mode'
  action:
  - service: script.message_night_mode
