## NIGHT LIGHT
- alias: message_night_light'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/night_light'
  action:
  - service: script.message_night_light
