## OCCUPANCY
- alias: message_occupancy'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/occupancy'
  action:
  - service: script.message_occupancy

- alias: 'message_occupancy_kitchen'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_kitchen_boolean'
  action:
  - service: script.message_occupancy_kitchen

- alias: 'message_occupancy_bath'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_bath_boolean'
  action:
  - service: script.message_occupancy_bath

- alias: 'message_occupancy_toilet'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy_toilet_boolean'
  action:
  - service: script.message_occupancy_toilet

- alias: 'message_occupancy_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_hall_boolean'
  action:
  - service: script.message_occupancy_hall
