## OCCUPANCY
- alias: message_occupancy'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/occupancy'
  action:
  - service: script.message_occupancy
