## PARTY LIGHT
- alias: message_party_light'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_party_light'
  action:
  - service: script.message_party_light
