## PRESSURE
- alias: message_pressure'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/pressure'
  action:
  - service: script.message_pressure
