## PRESSURE
- alias: pressure_temperature'
  initial_state: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/temperature'
  action:
  - service: script.pressure_temperature
