## OCCUPANCY
- alias: message_occupancy'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/security_occupancy'
  action:
  - service: script.message_occupancy

## WINDOW
- alias: message_window'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/security_window'
  action:
  - service: script.message_window

## DOORS
- alias: message_door'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/security_door'
  action:
  - service: script.message_door

- alias: 'message_door_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_hall_open'
  action:
  - service: script.message_door_hall

- alias: 'message_door_balcony'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_balcony_open'
  action:
  - service: script.message_door_balcony
