## SWITCH
- alias: message_switch'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_switch'
  action:
  - service: script.message_switch
