## SWITCH
- alias: message_switch'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/switch'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/switch'
  action:
  - service: script.message_switch
