## NAVIGATION SYSTEM
- alias: message_navigation_system'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/system'
  action:
  - service: script.message_navigation_system

## NAVIGATION SYSTEM NETWORK
- alias: message_navigation_system_network'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/system_network'
  action:
  - service: script.message_navigation_system_network

## NAVIGATION SYSTEM ERRORS
- alias: message_navigation_system_problems'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/system_problems'
  action:
  - service: script.message_navigation_system_problems

## NAVIGATION SYSTEM UPDATES
- alias: message_navigation_system_updates'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/system_updates'
  action:
  - service: script.message_navigation_updates

## NAVIGATION SYSTEM DATE TIME
- alias: message_navigation_system_date_time'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/system_date_time'
  action:
  - service: script.message_navigation_system_date_time

## MESSAGE SYSTEM START
- alias: 'system_start_message'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: script.message_system_start

## MESSAGE SYSTEM SHUTDOWN
- alias: 'system_shutdown_message'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: script.message_system_shutdown

## MESSAGE SYSTEM POWER
- alias: 'system_power_problem'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.rpi_power_status'
    to: 'on'
  action:
  - service: script.message_system_power_problem

## MESSAGE SYSTEM UPDATES
- alias: 'system_update_message'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'update.home_assistant_core_update'
    to: 'on'
  - platform: state
    entity_id: 'update.home_assistant_operating_system_update'
    to: 'on'
  - platform: state
    entity_id: 'update.home_assistant_supervisor_update'
    to: 'on'
  - platform: state
    entity_id: 'update.tailscale_update'
    to: 'on'
  - platform: state
    entity_id: 'update.zigbee2mqtt_update'
    to: 'on'
  - platform: state
    entity_id: 'update.mosquitto_broker_update'
    to: 'on'
  - platform: state
    entity_id: 'update.home_assistant_google_drive_backup_update'
    to: 'on'
  - platform: state
    entity_id: 'update.file_editor_update'
    to: 'on'
  - platform: state
    entity_id: 'update.terminal_ssh_update'
    to: 'on'
  action:
  - service: script.message_system_update
