## TEMPERATURE
- alias: message_temperature'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/temperature'
  action:
  - service: script.message_temperature
