## TEMPERATURE
- alias: message_temperature'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/temperature'
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/temperature'
  action:
  - service: script.message_temperature
