## NAVIGATION TOILET
- alias: message_navigation_toilet'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/toilet'
  action:
  - service: script.message_navigation_toilet

## NAVIGATION TOILET CLIMAT
- alias: message_navigation_toilet_climat'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/toilet_climat'
  action:
  - service: script.message_navigation_toilet_climat

## NAVIGATION TOILET LIGHT
- alias: message_navigation_toilet_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/toilet_light'
  action:
  - service: script.message_navigation_toilet_light
