## TOP LIGHT
- alias: message_top_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_groups'
  action:
  - service: script.message_top_light

- alias: message_top_light_kitchen'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_kitchen'
  action:
  - service: script.message_top_light_kitchen

- alias: message_top_light_bath'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_bath'
  action:
  - service: script.message_top_light_bath

- alias: message_top_light_toilet'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_toilet'
  action:
  - service: script.message_top_light_toilet

- alias: message_top_light_hall'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_hall'
  action:
  - service: script.message_top_light_hall

- alias: message_top_light_bedroom'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_bedroom'
  action:
  - service: script.message_top_light_bedroom

- alias: message_top_light_living'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/details_top_light_living'
  action:
  - service: script.message_top_light_living
