## VENTILATION
- alias: message_ventilation'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/ventilation'
  action:
  - service: script.message_ventilation
