## WINDOW
- alias: message_window'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/window'
  action:
  - service: script.message_window
