## WINDOW
- alias: message_window'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/window'
  action:
  - service: script.message_window

- alias: 'message_window_kitchen_left'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window_kitchen_left_open'
  action:
  - service: script.message_window_kitchen_left

- alias: 'message_window_kitchen_right'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window_kitchen_right_open'
  action:
  - service: script.message_window_kitchen_right

- alias: 'message_window_bedroom_left'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window_bedroom_left_open'
  action:
  - service: script.message_window_bedroom_left

- alias: 'message_window_bedroom_right'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window_bedroom_right_open'
  action:
  - service: script.message_window_bedroom_right

- alias: 'message_window_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window_living_open'
  action:
  - service: script.message_window_living
