icon: 'mdi:tune-variant'
cards:

## КНОПКИ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Кнопки'

  - type: entities  
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_boolean.button_kitchen_both
      name: 'Кухня вечеринка'
    - entity: input_boolean.button_kitchen_right 
      name: 'Кухня освещение'
    - entity: input_boolean.button_kitchen_left
      name: 'Кухня подсветка'
    - type: divider
    - entity: input_boolean.button_bath
      name: 'Ванная'
    - type: divider
    - entity: input_boolean.button_toilet
      name: 'Туалет'
    - type: divider
    - entity: input_boolean.button_hall 
      name: 'Коридор освещение'
    - entity: input_boolean.button_hall_both
      name: 'Коридор подсветка'
    - type: divider
    - entity: input_boolean.button_bedroom_right
      name: 'Спальня освещение'
    - entity: input_boolean.button_bedroom_left 
      name: 'Спальня подсветка'
    - type: divider
    - entity: input_boolean.button_living_right 
      name: 'Гостиная освещение'
    - entity: input_boolean.button_living_left
      name: 'Гостиная подсветка'
    - type: divider
    - entity: input_boolean.button_balcony_double 
      name: 'Балкон освещение'
    - entity: input_boolean.button_balcony_singl 
      name: 'Балкон подсветка'
    - entity: input_boolean.button_balcony_long 
      name: 'Балкон фонтан'
    - entity: input_boolean.button_balcony_shake 
      name: 'Балкон розетка'

## ВЫКЛЮЧАТЕЛИ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Выключатели'

  - type: entities  
    state_color: true
    show_header_toggle: false
    entities:
    - entity: switch.kitchen_switch_left
      name: 'Кухня освещение'
    - entity: switch.kitchen_switch_right
      name: 'Кухня подсветка'
    - type: divider
    - entity: switch.hall_switch_restroom_right
      name: 'Ванная'
    - type: divider
    - entity: switch.hall_switch_restroom_left
      name: 'Туалет'
    - type: divider
    - entity: switch.hall_switch
      name: 'Коридор'
    - type: divider
    - entity: switch.bedroom_switch
      name: 'Спальня освещение'
    - entity: switch.bedroom_wall_switch
      name: 'Спальня подсветка'
    - type: divider
    - entity: switch.living_switch
      name: 'Гостиная'

## РЕЛЕ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Реле'

  - type: entities  
    state_color: true
    show_header_toggle: false
    entities:
    - entity: switch.kitchen_relay_l2
      name: 'Кухня подсветка'
    - entity: switch.kitchen_relay_l1
      name: 'Кухня ночник'
    - type: divider
    - entity: switch.bath_relay_l1
      name: 'Ванная зеркало'
    - entity: switch.bath_relay_l2
      name: 'Ванная свободно'
    - type: divider
    - entity: switch.toilet_relay_l1
      name: 'Туалет вытяжка'
    - entity: switch.toilet_relay_l2
      name: 'Туалет ночник'
    - type: divider
    - entity: switch.hall_relay_l1
      name: 'Коридор подсветка'
    - entity: switch.hall_relay_l2
      name: 'Коридор увлажнитель' 
    - type: divider
    - entity: switch.bedroom_relay_l1
      name: 'Спальня подсветка'
    - entity: switch.bedroom_relay_l2
      name: 'Спальня увлажнитель'
    - type: divider
    - entity: switch.living_relay_l2
      name: 'Гостиная подсветка'
    - entity: switch.living_relay_l1
      name: 'Гостиная увлажнитель'
    - type: divider
    - entity: switch.balcony_relay_l2
      name: 'Балкон подсветка'
    - entity: switch.balcony_relay_l1
      name: 'Балкон ночник'
    - entity: switch.balcony_relay_l3
      name: 'Балкон фонтан'
    - entity: switch.balcony_relay_l4
      name: 'Балкон розетка'

## АВТОМАТИЗАЦИИ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Автоматизации'

  - type: entities  
    state_color: true
    show_header_toggle: false
    entities:
    - entity: automation.night_mode_auto
      name: 'Ночной режим'
    - type: divider
    - entity: automation.curtain_kitchen
      name: 'Кухня шторы'
    - entity: automation.party_light_kitchen
      name: 'Кухня вечеринка'
    - entity: automation.top_light_kitchen
      name: 'Кухня освещение'
    - entity: automation.back_light_kitchen
      name: 'Кухня посдветка'
    - entity: automation.night_light_kitchden
      name: 'Кухня ночник'
    - type: divider
    - entity: automation.top_light_bath
      name: 'Ванная освещение'
    - entity: automation.night_light_bath
      name: 'Ванная ночник'
    - entity: automation.dehumidifier_bath_on
      name: 'Ванная вытяжка'
    - type: divider
    - entity: automation.top_light_toilet
      name: 'Туалет ночник'
    - entity: automation.night_light_toilet
      name: 'Туалет ночник'
    - entity: automation.dehumidifier_toilet_on
      name: 'Туалет вытяжка'
    - type: divider
    - entity: automation.top_light_hall
      name: 'Коридор освещение'
    - entity: automation.top_light_hall 
      name: 'Коридор посдветка'
    - entity: automation.night_light_hall
      name: 'Коридор ночник'
    - entity: automation.humidifier_hall
      name: 'Коридор увлажнитель'
    - type: divider
    - entity: automation.curtain_bedroom
      name: 'Спальня шторы'
    - entity: automation.top_light_bedroom
      name: 'Спальня освещение'
    - entity: automation.back_light_bedroom_1
      name: 'Спальня подсветка'
    - entity: automation.back_light_bedroom_2
      name: 'Спальня светильник'
    - entity: automation.humidifier_bedroom
      name: 'Спальня увлажнитель'
    - type: divider
    - entity: automation.curtain_living
      name: 'Гостиная шторы'
    - entity: automation.top_light_living
      name: 'Гостиная освещение'
    - entity: automation.back_light_living
      name: 'Гостиная подсветка'
    - entity: automation.humidifier_living
      name: 'Гостиная увлажнитель'
    - type: divider
    - entity: automation.back_light_balcony
      name: 'Балкон освещение'
    - entity: automation.night_light_balcony
      name: 'Балкон подсветка'
    - entity: automation.fountain_balcony
      name: 'Балкон фонтан'
    - entity: automation.socket_balcony
      name: 'Балкон розетка'

## ВЛАЖНОСТЬ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Влажность'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.humidity_target
      name: 'Таргет'
    - entity: input_number.humidity_target_bath
      name: 'Таргет ванная'
    - entity: input_number.humidity_offset
      name: 'Офсет'

## ТЕМПЕРАТУРА
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Температура'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.temperature_target
      name: 'Таргет'
    - entity: input_number.temperature_offset
      name: 'Офсет'

## ДАВЛЕНИЕ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Давление'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.pressure_target
      name: 'Таргет'
    - entity: input_number.pressure_offset
      name: 'Офсет'

## ОБЛАЧНОСТЬ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Облачность'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.cloud_target
      name: 'Облачность таргет'

## НОЧНОЙ РЕЖИМ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Ночной режим'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.night_mode_inaction_target
      name: 'Время бездействия'

## ОСВЕЩЕННОСТЬ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Яркость солнца'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.parameters_light_target
      name: 'Максимальная яркость'

## ОСВЕЩЕННОСТЬ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Освещенность'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.illuminance_kitchen_curtain_target_sunny
      name: 'Шторы (солнечно)'
    - entity: input_number.illuminance_kitchen_curtain_target_cloudly
      name: 'Шторы (облачно)'
    - entity: input_number.illuminance_kitchen_top_light_target_sunny
      name: 'Освещение (солнечно)'
    - entity: input_number.illuminance_kitchen_top_light_target_cloudly
      name: 'Освещение (облачно)'
    - entity: input_number.illuminance_kitchen_back_light_target_sunny
      name: 'Подсветка (солнечно)'
    - entity: input_number.illuminance_kitchen_back_light_target_cloudly
      name: 'Подсветка (облачно)'
    - type: divider
    - entity: input_number.illuminance_hall_top_light_target_sunny
      name: 'Освещение (солнечно)'
    - entity: input_number.illuminance_hall_top_light_target_cloudly
      name: 'Освещение (облачно)'
    - entity: input_number.illuminance_hall_back_light_target_sunny
      name: 'Подсветка (солнечно)'
    - entity: input_number.illuminance_hall_back_light_target_cloudly
      name: 'Подсветка (облачно)'
    - type: divider
    - entity: input_number.illuminance_bedroom_curtain_target_sunny
      name: 'Шторы (солнечно)'
    - entity: input_number.illuminance_bedroom_curtain_target_cloudly
      name: 'Шторы (облачно)'
    - entity: input_number.illuminance_bedroom_back_light_target_sunny
      name: 'Подсветка (солнечно)'
    - entity: input_number.illuminance_bedroom_back_light_target_cloudly
      name: 'Подсветка (облачно)'
    - type: divider
    - entity: input_number.illuminance_living_curtain_target_sunny
      name: 'Шторы (солнечно)'
    - entity: input_number.illuminance_living_curtain_target_cloudly
      name: 'Шторы (облачно)'
    - entity: input_number.illuminance_living_back_light_target_sunny
      name: 'Подсветка (солнечно)'
    - entity: input_number.illuminance_living_back_light_target_cloudly
      name: 'Подсветка (облачно)'

## ШТОРЫ КУХНЯ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Шторы кухня'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.curtain_kitchen_ventilation
      name: 'Вентиляция'
    - entity: input_number.curtain_kitchen_night
      name: 'Ночь'
    - entity: input_number.curtain_kitchen_sun
      name: 'Солнечно'
    - entity: input_number.curtain_kitchen_open
      name: 'Открыто'
    - entity: input_number.curtain_kitchen_close
      name: 'Закрыто'

## ШТОРЫ СПАЛЬНЯ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Шторы спальня'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.curtain_bedroom_ventilation
      name: 'Вентиляция'
    - entity: input_number.curtain_bedroom_night
      name: 'Ночь'
    - entity: input_number.curtain_bedroom_sun
      name: 'Солнечно'
    - entity: input_number.curtain_bedroom_open
      name: 'Открыто'
    - entity: input_number.curtain_bedroom_close
      name: 'Закрыто'

## ШТОРЫ ГОСТИНАЯ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Шторы гостиная'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.curtain_living_ventilation
      name: 'Вентиляция'
    - entity: input_number.curtain_living_night
      name: 'Ночь'
    - entity: input_number.curtain_living_sun
      name: 'Солнечно'
    - entity: input_number.curtain_living_open
      name: 'Открыто'
    - entity: input_number.curtain_living_close
      name: 'Закрыто'

## СОЛНЦЕ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Солнце'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.solar_azimuth_target
      name: 'Таргет (азимут)'
    - entity: input_number.solar_azimuth_offset
      name: 'Офсет (азимут)'
    - type: divider
    - entity: input_number.solar_elevation_target
      name: 'Таргет (офсет)'
    - entity: input_number.solar_elevation_offset
      name: 'Офсет (офсет)'

## МОЩНОСТЬ ПОДСВЕТКИ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Мощность подсветки'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.power_offset_hall
      name: 'Коридор'
    - entity: input_number.power_offset_bedroom
      name: 'Спальня'
    - entity: input_number.power_offset_living
      name: 'Гостиная'

## ЗАДЕРЖКА
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Задержка'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.delay_power_on
      name: 'Питание'
    - entity: input_number.delay_ventilation_on
      name: 'Вентиляция (вкл)'
    - entity: input_number.delay_ventilation_off
      name: 'Вентиляция (выкл)'
    - entity: input_number.delay_illuminance_on
      name: 'Освещенность (вкл)'
    - entity: input_number.delay_illuminance_off
      name: 'Освещенность (выкл)'
    - entity: input_number.delay_motion_night_off
      name: 'Движение выкл (ночь)'
    - entity: input_number.delay_motion_day_off
      name: 'Движение выкл (день)'
    - entity: input_number.delay_night_mode_on
      name: 'Ночной режим вкл'

## ДЛИТЕЛЬНОСТЬ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Длительность'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.duration_dehumidifier_night
      name: 'Вытяжка (ночь)'
    - entity: input_number.duration_dehumidifier_day
      name: 'Вытяжка (день)'
    - entity: input_number.duration_light_night
      name: 'Освещение (ночь)'
    - entity: input_number.duration_light_day
      name: 'Освещение (день)'
    - entity: input_number.duration_toilet_mode
      name: 'Режим туалета'
    - entity: input_number.duration_dorbell
      name: 'Дверной звонок'

## СЕТЬ
- type: vertical-stack
  cards:
  - type: markdown
    content: 'Сеть'

  - type: entities
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_number.network_download_target
      name: 'Загрузка'
    - entity: input_number.network_upload_target
      name: 'Отдача'
    - entity: input_number.network_ping_target
      name: 'Пинг'
