title: 'Параметры'
icon: 'mdi:tune-variant'
cards:
- type: vertical-stack
  cards:

  - type: entities  
    title: 'Сеть'
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_boolean.button_kitchen_both
      name: 'Кухня вечеринка'
    - entity: input_boolean.button_kitchen_left
      name: 'Кухня освещение'
    - entity: input_boolean.button_kitchen_right
      name: 'Кухня подсветка'
    - entity: input_boolean.button_bath
      name: 'Ванная освещение'
    - entity: input_boolean.button_toilet
      name: 'Туалет освещение'
    - entity: input_boolean.button_toilet_long
      name: 'Туалет вытяжка'
    - entity: input_boolean.button_hall
      name: 'Коридор освещение'
    - entity: input_boolean.button_hall_both
      name: 'Коридор подсветка'
    - entity: input_boolean.button_bedroom_left
      name: 'Спальня освещение'
    - entity: input_boolean.button_bedroom_right
      name: 'Спальня подсветка'
    - entity: input_boolean.button_living_left
      name: 'Гостиная освещение'
    - entity: input_boolean.button_living_right
      name: 'Гостиная подсветка'
    - entity: input_boolean.button_balcony_singl
      name: 'Балкон освещение'
    - entity: input_boolean.button_balcony_double
      name: 'Балкон подсветка'
    - entity: input_boolean.button_balcony_long
      name: 'Балкон фонтан'
    - entity: input_boolean.button_balcony_shake
      name: 'Балкон розетка'

- type: vertical-stack
  cards:

  - type: entities
    title: 'Ночной режим'
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_boolean.button_bedroom_both
      name: 'Спальня'
    - entity: input_boolean.button_living_both
      name: 'Гостиная'
    - type: devider
    - entity: input_dateTime.night_mode_start_time
      name: 'Начало'
    - entity: input_dateTime.night_mode_stop_time
      name: 'Конец'

  - type: entities
    title: 'Время суток'
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_dateTime.date_time_night_time
      name: 'Ночь'
    - entity: input_dateTime.date_time_morning_time
      name: 'Утро'
    - entity: input_dateTime.date_time_day_time
      name: 'День'
    - entity: input_dateTime.date_time_evening_time
      name: 'Вечер'

  - type: entities
    title: 'Оффсет и Таргет'
    state_color: true
    show_header_toggle: false
    entities:
    - entity: input_boolean.cloud_target
      name: 'Облачность'
    - entity: input_boolean.humidity_target
      name: 'Гостиная'
    - entity: input_boolean.humidity_target_bath
      name: 'Гостиная'
    - entity: input_boolean.humidity_offset
      name: 'Гостиная'
