## CURTAIN
- alias: 'curtain_kitchen'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.curtain_kitchen_level'
  action:
  - service: script.curtain_kitchen_set_position
    data_template:
      position: "{{ states('sensor.curtain_kitchen_level') | int(0) }}"

- alias: 'curtain_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.curtain_bedroom_level'
  action:
  - service: script.curtain_bedroom_set_position
    data_template:
      position: "{{ states('sensor.curtain_bedroom_level') | int(0) }}"

- alias: 'curtain_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.curtain_living_level'
  action:
  - service: script.curtain_living_set_position
    data_template:
      position: "{{ states('sensor.curtain_living_level') | int(0) }}"
