## DEHUMIDIFIER
- alias: 'dehumidifier_toilet'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.dehumidifier_toilet_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.dehumidifier_toilet_permission
        state: 'on'
      sequence:
      - service: script.dehumidifier_toilet_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.dehumidifier_toilet_permission
        state: 'off'
      sequence:
      - service: script.dehumidifier_toilet_off
