## FOUNTAIN
- alias: 'fountain_balcony'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.fountain_balcony_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.fountain_balcony_permission
        state: 'on'
      sequence:
      - service: script.fountain_balcony_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.fountain_balcony_permission
        state: 'off'
      sequence:
      - service: script.fountain_balcony_off
