## TOP LIGHT
- alias: 'top_light_kitchen'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.top_light_kitchen_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_kitchen_left_on
        state: 'on'
      - condition: state
        entity_id: binary_sensor.top_light_kitchen_permission
        state: 'on'
      sequence:
      - service: script.top_light_kitchen_1_on
      - service: script.top_light_kitchen_2_on
      - service: script.top_light_kitchen_3_on
      - service: script.top_light_kitchen_4_on
      - service: script.top_light_kitchen_5_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_kitchen_left_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.top_light_kitchen_permission
        state: 'off'
      sequence:
      - service: script.top_light_kitchen_1_off
      - service: script.top_light_kitchen_2_off
      - service: script.top_light_kitchen_3_off
      - service: script.top_light_kitchen_4_off
      - service: script.top_light_kitchen_5_off

- alias: 'top_light_bath'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.top_light_bath_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.top_light_bath_permission
        state: 'on'
      sequence:
      - service: script.top_light_bath_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.top_light_bath_permission
        state: 'off'
      sequence:
      - service: script.top_light_bath_off

- alias: 'top_light_toilet'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.top_light_toilet_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.top_light_toilet_permission
        state: 'on'
      sequence:
      - service: script.top_light_toilet_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.top_light_toilet_permission
        state: 'off'
      sequence:
      - service: script.top_light_toilet_off

- alias: 'top_light_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.top_light_hall_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_hall_on
        state: 'on'
      - condition: state
        entity_id: binary_sensor.top_light_hall_permission
        state: 'on'
      sequence:
      - service: script.top_light_hall_1_on
      - service: script.top_light_hall_2_on
      - service: script.top_light_hall_3_on
      - service: script.top_light_hall_4_on
      - service: script.top_light_hall_5_on
      - service: script.top_light_hall_6_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_hall_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.top_light_hall_permission
        state: 'off'
      sequence:
      - service: script.top_light_hall_1_off
      - service: script.top_light_hall_2_off
      - service: script.top_light_hall_3_off
      - service: script.top_light_hall_4_off
      - service: script.top_light_hall_5_off
      - service: script.top_light_hall_6_off

- alias: 'top_light_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.top_light_bedroom_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_bedroom_on
        state: 'on'
      - condition: state
        entity_id: binary_sensor.top_light_bedroom_permission
        state: 'on'
      sequence:
      - service: script.top_light_bedroom_1_on
      - service: script.top_light_bedroom_2_on
      - service: script.top_light_bedroom_3_on
      - service: script.top_light_bedroom_4_on
      - service: script.top_light_bedroom_5_on
      - service: script.top_light_bedroom_6_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_bedroom_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.top_light_bedroom_permission
        state: 'on'
      sequence:
      - service: script.top_light_bedroom_1_off
      - service: script.top_light_bedroom_2_off
      - service: script.top_light_bedroom_3_off
      - service: script.top_light_bedroom_4_off
      - service: script.top_light_bedroom_5_off
      - service: script.top_light_bedroom_6_off

- alias: 'top_light_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.top_light_living_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_living_on
        state: 'on'
      - condition: state
        entity_id: binary_sensor.top_light_living_permission
        state: 'on'
      sequence:
      - service: script.top_light_living_1_on
      - service: script.top_light_living_2_on
      - service: script.top_light_living_3_on
      - service: script.top_light_living_4_on
      - service: script.top_light_living_5_on
      - service: script.top_light_living_6_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.switch_living_on
        state: 'off'
      - condition: state
        entity_id: binary_sensor.top_light_living_permission
        state: 'off'
      sequence:
      - service: script.top_light_living_1_off
      - service: script.top_light_living_2_off
      - service: script.top_light_living_3_off
      - service: script.top_light_living_4_off
      - service: script.top_light_living_5_off
      - service: script.top_light_living_6_off
