## HUMIDIFIER
- alias: 'notification_humidifier_empty_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.humidifier_hall_empty_boolean'
  action:
  - service: script.notification_homepod
    data_template:
      message: "{{ states('input_text.problem_empty_hall') }}"

- alias: 'notification_humidifier_empty_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.humidifier_bedroom_empty_boolean'
  action:
  - service: script.notification_homepod
    data_template:
      message: "{{ states('input_text.problem_empty_bedroom') }}"

- alias: 'notification_humidifier_empty_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.humidifier_living_empty_boolean'
  action:
  - service: script.notification_homepod
    data_template:
      message: "{{ states('input_text.problem_empty_living') }}"
