## HALL
- alias: 'e_hall_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.empty'
    attribute: 'hall'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.empty'
    attribute: 'hall'
    from: true
    to: false
  action:
  - service: script.e_hall_timer_cancel
  - service: script.e_hall_timer_start

- alias: 'e_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.e_hall
  condition:
  - condition: state
    entity_id: 'binary_sensor.empty'
    attribute: 'hall'
    state: true
  action:
  - service: script.e_hall_boolean_on

- alias: 'e_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.e_hall
  condition:
  - condition: state
    entity_id: 'binary_sensor.empty'
    attribute: 'hall'
    state: false
  action:
  - service: script.e_hall_boolean_off


  ## BEDROOM
- alias: 'e_bedroom_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.empty'
    attribute: 'bedroom'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.empty'
    attribute: 'bedroom'
    from: true
    to: false
  action:
  - service: script.e_bedroom_timer_cancel
  - service: script.e_bedroom_timer_start

- alias: 'e_bedroom_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.e_bedroom
  condition:
  - condition: state
    entity_id: 'binary_sensor.empty'
    attribute: 'bedroom'
    state: true
  action:
  - service: script.e_bedroom_boolean_on

- alias: 'e_bedroom_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.e_bedroom
  condition:
  - condition: state
    entity_id: 'binary_sensor.empty'
    attribute: 'bedroom'
    state: false
  action:
  - service: script.e_bedroom_boolean_off


## LIVING
- alias: 'e_living_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.empty'
    attribute: 'living'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.empty'
    attribute: 'living'
    from: true
    to: false
  action:
  - service: script.e_living_timer_cancel
  - service: script.e_living_timer_start

- alias: 'e_living_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.e_living
  condition:
  - condition: state
    entity_id: 'binary_sensor.empty'
    attribute: 'living'
    state: true
  action:
  - service: script.e_living_boolean_on

- alias: 'e_living_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.e_living
  condition:
  - condition: state
    entity_id: 'binary_sensor.empty'
    attribute: 'living'
    state: false
  action:
  - service: script.e_living_boolean_off
