## KITCHEN
- alias: 'v_kitchen_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'kitchen'
    from: 'off'
    to: 'on'
  action:
  - service: script.v_kitchen_boolean_on

- alias: 'v_kitchen_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'kitchen'
    from: 'on'
    to: 'off'
  action:
  - service: script.v_kitchen_boolean_off


## HALL
- alias: 'v_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'hall'
    from: 'off'
    to: 'on'
  action:
  - service: script.v_hall_boolean_on

- alias: 'v_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'hall'
    from: 'on'
    to: 'off'
  action:
  - service: script.v_hall_boolean_off


## BEDROOM
- alias: 'v_bedroom_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'bedroom'
    from: 'off'
    to: 'on'
  action:
  - service: script.v_bedroom_boolean_on

- alias: 'v_bedroom_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'bedroom'
    from: 'on'
    to: 'off'
  action:
  - service: script.v_bedroom_boolean_off


## LIVING
- alias: 'v_living_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'living'
    from: 'off'
    to: 'on'
  action:
  - service: script.v_living_boolean_on

- alias: 'v_living_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation'
    attribute: 'living'
    from: 'on'
    to: 'off'
  action:
  - service: script.v_living_boolean_off
