- name: l_bedroom_1
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_1_host
  token: !secret bedroom_lamp_1_token
- name: l_bedroom_2
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_2_host
  token: !secret bedroom_lamp_2_token
- name: l_bedroom_3
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_3_host
  token: !secret bedroom_lamp_3_token
- name: l_bedroom_4
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_4_host
  token: !secret bedroom_lamp_4_token
- name: l_bedroom_5
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_5_host
  token: !secret bedroom_lamp_5_token
- name: l_bedroom_6
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_6_host
  token: !secret bedroom_lamp_6_token
- platform: group
  name: l_bedroom
  entities:
  - light.l_bedroom_1
  - light.l_bedroom_2
  - light.l_bedroom_3
  - light.l_bedroom_4
  - light.l_bedroom_5
  - light.l_bedroom_6