- name: tl_kitchen_1
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_1_host
  token: !secret kitchen_lamp_1_token
- name: tl_kitchen_2
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_2_host
  token: !secret kitchen_lamp_2_token
- name: tl_kitchen_3
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_3_host
  token: !secret kitchen_lamp_3_token
- name: tl_kitchen_4
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_4_host
  token: !secret kitchen_lamp_4_token
- name: tl_kitchen_5
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_5_host
  token: !secret kitchen_lamp_5_token
- platform: group
  name: tl_kitchen
  entities:
  - light.tl_kitchen_1
  - light.tl_kitchen_2
  - light.tl_kitchen_3
  - light.tl_kitchen_4
  - light.tl_kitchen_5