- name: tl_living_1
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret living_lamp_1_host
  token: !secret living_lamp_1_token
- name: tl_living_2
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret living_lamp_2_host
  token: !secret living_lamp_2_token
- name: tl_living_3
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret living_lamp_3_host
  token: !secret living_lamp_3_token
- name: tl_living_4
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret living_lamp_4_host
  token: !secret living_lamp_4_token
- name: tl_living_5
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret living_lamp_5_host
  token: !secret living_lamp_5_token
- name: tl_living_6
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret living_lamp_6_host
  token: !secret living_lamp_6_token
- platform: group
  name: tl_living
  entities:
  - light.tl_living_1
  - light.tl_living_2
  - light.tl_living_3
  - light.tl_living_4
  - light.tl_living_5
  - light.tl_living_6