- platform: template
  covers:
    living:
      device_class: 'curtain'
      value_template: '{{ states("sensor.c_kitchen") | int > 0 }}'
      position_template: '{{ state_attr("cover.curtain_kitchen", "position") | int(0) }}'
      open_cover:
      - service: cover.set_cover_position
        entity_id: cover.curtain_kitchen
        data_template:
          position: '{{ states("input_number.curtain_kitchen_position_open") }}'
      close_cover:
      - service: cover.set_cover_position
        entity_id: cover.curtain_kitchen
        data_template:
          position: '{{ states("input_number.curtain_kitchen_position_night") }}'
      set_cover_position:
      - service: cover.set_cover_position
        entity_id: cover.curtain_kitchen
        data_template:
          position: '{{ position }}'