- platform: template
  switches:
    bedroom_switch:
      value_template: "{{ is_state('binary_sensor.switch_bedroom_on', 'on') }}"
      turn_on:
      - service: switch.turn_on
        data:
          entity_id: switch.bedroom_switch_left, switch.bedroom_switch_right
      turn_off:
      - service: switch.turn_off
        data:
          entity_id: switch.bedroom_switch_left, switch.bedroom_switch_right
