- platform: template
  switches:
    kitchen_switch:
      value_template: "{{ is_state('binary_sensor.switch_kitchen_on', 'on') }}"
      turn_on:
      - service: switch.turn_on
        data:
          entity_id: switch.kitchen_switch_left, switch.kitchen_switch_right
      turn_off:
      - service: switch.turn_off
        data:
          entity_id: switch.kitchen_switch_left, switch.kitchen_switch_right
