light.light_back_kitchen:
  name: Подсветка

light.light_back_bath:
  name: Подсветка

light.light_back_toilet:
  name: Подсветка

light.light_back_hall:
  name: Подсветка

light.light_back_bedroom:
  name: Подсветка

light.light_back_living:
  name: Подсветка

light.light_back_balcony:
  name: Подсветка
