light.back_light_kitchen:
  name: Back Light

light.back_light_hall:
  name: Back Light

light.back_light_bedroom:
  name: Back Light

light.back_light_living:
  name: Back Light

light.back_light_balcony:
  name: Back Light
