switch.kitchen_relay_l2:
  name: Back Light Kitchen

switch.hall_relay_l1:
  name: Back Light Hall

switch.bedroom_relay_l1:
  name: Back Light Bedroom

switch.bedroom_wall_switch:
  name: Back Light Bedroom

switch.living_relay_l2:
  name: Back Light Living

switch.balcony_relay_l2:
  name: Back Light Balcony