switch.kitchen_relay_l2:
  name: Back Light

switch.hall_relay_l1:
  name: Back Light

switch.bedroom_relay_l1:
  name: Back Light

switch.bedroom_wall_switch:
  name: Wall Light

switch.living_relay_l2:
  name: Back Light

switch.balcony_relay_l2:
  name: Back Light