input_boolean.blocker_back_light_kitchen:
  name: Подсветка

light.back_light_hall:
  name: Подсветка

light.back_light_bedroom:
  name: Подсветка

light.back_light_living:
  name: Подсветка

light.back_light_balcony:
  name: Подсветка
