light.bulb_light_kitchen:
  name: Освещение
light.bulb_light_kitchen_1:
  name: Светильник 1
light.bulb_light_kitchen_2:
  name: Светильник 2
light.bulb_light_kitchen_3:
  name: Светильник 3
light.bulb_light_kitchen_4:
  name: Светильник 4
light.bulb_light_kitchen_5:
  name: Светильник 5

light.bulb_light_hall:
  name: Освещение
light.bulb_light_hall_1:
  name: Светильник 1
light.bulb_light_hall_2:
  name: Светильник 2
light.bulb_light_hall_3:
  name: Светильник 3
light.bulb_light_hall_4:
  name: Светильник 4
light.bulb_light_hall_5:
  name: Светильник 5
light.bulb_light_hall_6:
  name: Светильник 6

light.bulb_light_bedroom:
  name: Освещение
light.bulb_light_bedroom_1:
  name: Светильник 1
light.bulb_light_bedroom_2:
  name: Светильник 2
light.bulb_light_bedroom_3:
  name: Светильник 3
light.bulb_light_bedroom_4:
  name: Светильник 4
light.bulb_light_bedroom_5:
  name: Светильник 5
light.bulb_light_bedroom_6:
  name: Светильник 6

light.bulb_light_living:
  name: Освещение
light.bulb_light_living_1:
  name: Светильник 1
light.bulb_light_living_2:
  name: Светильник 2
light.bulb_light_living_3:
  name: Светильник 3
light.bulb_light_living_4:
  name: Светильник 4
light.bulb_light_living_5:
  name: Светильник 5
light.bulb_light_living_6:
  name: Светильник 6
