light.bulb_light_kitchen:
  name: Освещение

light.bulb_light_bath:
  name: Освещение

light.bulb_light_toilet:
  name: Освещение

light.bulb_light_hall:
  name: Освещение

light.bulb_light_bedroom:
  name: Освещение

light.bulb_light_living:
  name: Освещение
