binary_sensor.door_toilet_open:
  name: Door

binary_sensor.door_hall_open:
  name: Door

binary_sensor.door_bedroom_open:
  name: Door

binary_sensor.door_living_open:
  name: Door

binary_sensor.door_balcony_open:
  name: Door