binary_sensor.door_bath:
  name: Дверь

binary_sensor.door_toilet:
  name: Дверь

binary_sensor.door_hall:
  name: Дверь

binary_sensor.door_bedroom:
  name: Дверь

binary_sensor.door_living:
  name: Дверь

binary_sensor.door_balcony:
  name: Дверь
