humidifier.humidifier_hall:
  name: Humidifier

humidifier.humidifier_bedroom:
  name: Humidifier

humidifier.humidifier_living:
  name: Humidifier

binary_sensor.hygrostat_hall_is_empty:
  name: Full humidifier

binary_sensor.hygrostat_bedroom_is_empty:
  name: Full humidifier

binary_sensor.hygrostat_living_is_empty:
  name: Full humidifier
