sensor.climat_humidity_kitchen_virtual:
  name: Влажность

sensor.climat_humidity_bath_virtual:
  name: Влажность

sensor.climat_humidity_toilet_virtual:
  name: Влажность

sensor.climat_humidity_hall_virtual:
  name: Влажность

sensor.climat_humidity_bedroom_virtual:
  name: Влажность

sensor.climat_humidity_living_virtual:
  name: Влажность

sensor.climat_humidity_balcony_virtual:
  name: Влажность
