sensor.humidity_kitchen_virtual:
  name: Влажность

sensor.humidity_bath_virtual:
  name: Влажность

sensor.humidity_toilet_virtual:
  name: Влажность

sensor.humidity_hall_virtual:
  name: Влажность

sensor.humidity_bedroom_virtual:
  name: Влажность

sensor.humidity_living_virtual:
  name: Влажность

sensor.humidity_balcony_virtual:
  name: Влажность
