humidifier.humidifier_hall:
  name: Humidifier
  linked_humidity_sensor: sensor.humidity_hall

humidifier.humidifier_bedroom:
  name: Humidifier
  linked_humidity_sensor: sensor.humidity_bedroom

humidifier.humidifier_living:
  name: Humidifier
  linked_humidity_sensor: sensor.humidity_living

binary_sensor.hygrostat_hall_is_empty:
  name: Full humidifier

binary_sensor.hygrostat_bedroom_is_empty:
  name: Full humidifier

binary_sensor.hygrostat_living_is_empty:
  name: Full humidifier
