sensor.humidity_kitchen_level:
  name: Humidity

sensor.humidity_bath_level:
  name: Humidity

sensor.humidity_hall_level:
  name: Humidity

sensor.humidity_bedroom_level:
  name: Humidity

sensor.humidity_living_level:
  name: Humidity

sensor.humidity_balcony_level:
  name: Humidity