sensor.illuminance_balcony_level:
  name: Illuminance
  linked_battery_sensor: sensor.balcony_illuminance_battery

sensor.illuminance_kitchen_level:
  name: Illuminance
  linked_battery_sensor: sensor.kitchen_motion_battery

sensor.illuminance_hall_level:
  name: Illuminance
  linked_battery_sensor: sensor.hall_motion_battery
