light.night_light_kitchen:
  name: Ночник

light.night_light_bath:
  name: Ночник

light.night_light_toilet:
  name: Ночник

light.night_light_hall:
  name: Ночник

light.night_light_balcony:
  name: Ночник