switch.kitchen_relay_l1:
  name: Night Light

switch.bath_relay_l1:
  name: Night Light

switch.toilet_relay_l2:
  name: Night Light

light.nightlight_hall:
  name: Night Light

switch.night_light_balcony:
  name: Night Light