light.night_light_kitchen:
  name: Night Light

light.night_light_bath:
  name: Night Light

light.night_light_toilet:
  name: Night Light

light.nightlight_hall:
  name: Night Light

light.night_light_balcony:
  name: Night Light