binary_sensor.occupancy_kitchen:
  name: Движение

binary_sensor.occupancy_bath:
  name: Движение

binary_sensor.occupancy_toilet:
  name: Движение

binary_sensor.occupancy_hall:
  name: Движение

binary_sensor.occupancy_balcony:
  name: Присутствие
