binary_sensor.motion_kitchen_boolean:
  name: Occupancy

binary_sensor.motion_bath_boolean:
  name: Occupancy

binary_sensor.occupancy_toilet_boolean:
  name: Occupancy

binary_sensor.motion_hall_boolean:
  name: Occupancy