binary_sensor.motion_kitchen_boolean:
  name: Occupancy
  linked_battery_sensor: sensor.kitchen_motion_battery

binary_sensor.motion_bath_boolean:
  name: Occupancy
  linked_battery_sensor: sensor.bath_motion_battery

binary_sensor.motion_hall_boolean:
  name: Occupancy
  linked_battery_sensor: sensor.hall_motion_battery

binary_sensor.occupancy_toilet_boolean:
  name: Occupancy
