sensor.pressure_kitchen_level:
  name: pressure_kitchen_level

sensor.pressure_bath_level:
  name: pressure_bath_level

sensor.pressure_hall_level:
  name: pressure_hall_level

sensor.pressure_bedroom_level:
  name: pressure_bedroom_level

sensor.pressure_living_level:
  name: pressure_living_level
