switch.kitchen_switch:
  name: Switch

switch.hall_switch_restroom_right:
  name: Switch

switch.hall_switch_restroom_left:
  name: Switch

switch.hall_switch:
  name: Switch

switch.bedroom_switch:
  name: Switch

switch.living_switch:
  name: Switch