sensor.temperature_kitchen_level:
  name: Temperature
  linked_battery_sensor: sensor.kitchen_thermometer_battery

sensor.temperature_bath_level:
  name: Temperature
  linked_battery_sensor: sensor.bath_thermometer_battery

sensor.temperature_hall_level:
  name: Temperature
  linked_battery_sensor: sensor.hall_thermometer_battery

sensor.temperature_bedroom_level:
  name: Temperature
  linked_battery_sensor: sensor.bedroom_thermometer_battery

sensor.temperature_living_level:
  name: Temperature
  linked_battery_sensor: sensor.living_thermometer_battery

sensor.temperature_balcony_level:
  name: Temperature
  linked_battery_sensor: sensor.ble_battery_balcony