sensor.temperature_kitchen_level:
  name: Temperature
  linked_humidity_sensor: sensor.humidity_kitchen_level

sensor.temperature_bath_level:
  name: Temperature
  linked_humidity_sensor: sensor.humidity_bath_level

sensor.temperature_hall_level:
  name: Temperature
  linked_humidity_sensor: sensor.humidity_hall_level

sensor.temperature_bedroom_level:
  name: Temperature
  linked_humidity_sensor: sensor.humidity_bedroom_level

sensor.temperature_living_level:
  name: Temperature
  linked_humidity_sensor: sensor.humidity_living_level

sensor.temperature_balcony_level:
  name: Temperature
  linked_humidity_sensor: sensor.humidity_balcony_level