sensor.climat_temperature_kitchen_virtual:
  name: Температура

sensor.climat_temperature_bath_virtual:
  name: Температура

sensor.climat_temperature_toilet_virtual:
  name: Температура

sensor.climat_temperature_hall_virtual:
  name: Температура

sensor.climat_temperature_bedroom_virtual:
  name: Температура

sensor.climat_temperature_living_virtual:
  name: Температура

sensor.climat_temperature_balcony_virtual:
  name: Температура

sensor.system_monitor_processor_temperature:
  name: Процессор