sensor.temperature_kitchen:
  name: Температура

sensor.temperature_bath:
  name: Температура

sensor.temperature_hall:
  name: Температура

sensor.temperature_bedroom:
  name: Температура

sensor.temperature_living:
  name: Температура

sensor.temperature_balcony:
  name: Температура
