sensor.temperature_kitchen_virtual:
  name: Температура

sensor.temperature_bath_virtual:
  name: Температура

sensor.temperature_toilet_virtual:
  name: Температура

sensor.temperature_hall_virtual:
  name: Температура

sensor.temperature_bedroom_virtual:
  name: Температура

sensor.temperature_living_virtual:
  name: Температура

sensor.temperature_balcony_virtual:
  name: Температура
