sensor.temperature_kitchen_level:
  name: Temperature

sensor.temperature_bath_level:
  name: Temperature

sensor.temperature_hall_level:
  name: Temperature

sensor.temperature_bedroom_level:
  name: Temperature

sensor.temperature_living_level:
  name: Temperature

sensor.temperature_balcony_level:
  name: Temperature