light.top_light_kitchen_group:
  name: Top Light

light.top_light_kitchen_1:
  name: Top Light 1

light.top_light_kitchen_2:
  name: Top Light 2

light.top_light_kitchen_3:
  name: Top Light 3

light.top_light_kitchen_4:
  name: Top Light 4

light.top_light_kitchen_5:
  name: Top Light 5


light.top_light_hall_group:
  name: Top Light

light.top_light_hall_1:
  name: Top Light 1

light.top_light_hall_2:
  name: Top Light 2

light.top_light_hall_3:
  name: Top Light 3

light.top_light_hall_4:
  name: Top Light 4

light.top_light_hall_5:
  name: Top Light 5

light.top_light_hall_6:
  name: Top Light 6


light.top_light_bedroom_group:
  name: Top Light

light.top_light_bedroom_1:
  name: Top Light 1

light.top_light_bedroom_2:
  name: Top Light 2

light.top_light_bedroom_3:
  name: Top Light 3

light.top_light_bedroom_4:
  name: Top Light 4

light.top_light_bedroom_5:
  name: Top Light 5

light.top_light_bedroom_6:
  name: Top Light 6


light.top_light_living_group:
  name: Top Light

light.top_light_living_1:
  name: Top Light 1

light.top_light_living_2:
  name: Top Light 2

light.top_light_living_3:
  name: Top Light 3

light.top_light_living_4:
  name: Top Light 4

light.top_light_living_5:
  name: Top Light 5

light.top_light_living_6:
  name: Top Light 6