light.top_light_kitchen_group:
  name: Top Light

light.top_light_bath:
  name: Top Light

light.top_light_toilet:
  name: Top Light

light.top_light_hall_group:
  name: Top Light

light.top_light_bedroom_group:
  name: Top Light

light.top_light_living_group:
  name: Top Light
