input_boolean.blocker_top_light_kitchen:
  name: Свет

input_boolean.blocker_top_light_bath:
  name: Свет

light.top_light_toilet:
  name: Свет

input_boolean.blocker_top_light_hall:
  name: Свет

light.top_light_bedroom:
  name: Свет

light.top_light_living:
  name: Свет