light.light_top_kitchen:
  name: Свет

light.light_top_bath:
  name: Свет

light.light_top_toilet:
  name: Свет

light.light_top_hall:
  name: Свет

light.light_top_bedroom:
  name: Свет

light.light_top_living:
  name: Свет

light.light_top_balcony:
  name: Свет
