light.top_light_kitchen:
  name: Top Light

light.top_light_bath:
  name: Top Light

light.top_light_toilet:
  name: Top Light

light.top_light_hall:
  name: Top Light

light.top_light_bedroom:
  name: Top Light

light.top_light_living:
  name: Top Light
