light.top_light_kitchen_group:
  name: Top Light Kitchen

light.top_light_kitchen_1:
  name: Top Light Kitchen 1

light.top_light_kitchen_2:
  name: Top Light Kitchen 2

light.top_light_kitchen_3:
  name: Top Light Kitchen 3

light.top_light_kitchen_4:
  name: Top Light Kitchen 4

light.top_light_kitchen_5:
  name: Top Light Kitchen 5


light.top_light_hall_group:
  name: Top Light Hall

light.top_light_hall_1:
  name: Top Light Hall 1

light.top_light_hall_2:
  name: Top Light Hall 2

light.top_light_hall_3:
  name: Top Light Hall 3

light.top_light_hall_4:
  name: Top Light Hall 4

light.top_light_hall_5:
  name: Top Light Hall 5

light.top_light_hall_6:
  name: Top Light Hall 6


light.top_light_bedroom_group:
  name: Top Light Bedroom

light.top_light_bedroom_1:
  name: Top Light Bedroom 1

light.top_light_bedroom_2:
  name: Top Light Bedroom 2

light.top_light_bedroom_3:
  name: Top Light Bedroom 3

light.top_light_bedroom_4:
  name: Top Light Bedroom 4

light.top_light_bedroom_5:
  name: Top Light Bedroom 5

light.top_light_bedroom_6:
  name: Top Light Bedroom 6


light.top_light_living_group:
  name: Top Light Living

light.top_light_living_1:
  name: Top Light Living 1

light.top_light_living_2:
  name: Top Light Living 2

light.top_light_living_3:
  name: Top Light Living 3

light.top_light_living_4:
  name: Top Light Living 4

light.top_light_living_5:
  name: Top Light Living 5

light.top_light_living_6:
  name: Top Light Living 6