input_boolean.top_light_kitchen_blocker:
  name: Свет

input_boolean.top_light_bath_blocker:
  name: Свет

light.top_light_toilet:
  name: Свет

input_boolean.top_light_hall_blocker:
  name: Свет

light.top_light_bedroom:
  name: Свет

light.top_light_living:
  name: Свет