binary_sensor.window_kitchen_left_open:
  name: Window Left
  linked_battery_sensor: sensor.ble_battery_balcony

binary_sensor.window_kitchen_right_open:
  name: Window Right
  linked_battery_sensor: sensor.ble_battery_balcony

binary_sensor.window_bedroom_left_open:
  name: Window Left
  linked_battery_sensor: sensor.ble_battery_balcony

binary_sensor.window_bedroom_right_open:
  name: Window Right
  linked_battery_sensor: sensor.ble_battery_balcony

binary_sensor.window_living_open:
  name: Window
  linked_battery_sensor: sensor.ble_battery_balcony
