binary_sensor.window_kitchen_left_virtual:
  name: Левое Окно

binary_sensor.window_kitchen_right_virtual:
  name: Правое Окно 

binary_sensor.window_bedroom_left_virtual:
  name: Левое Окно

binary_sensor.window_bedroom_right_virtual:
  name: Правое Окно

binary_sensor.window_living_virtual:
  name: Окно
