binary_sensor.contact_kitchen_window_left_virtual:
  name: Левое Окно

binary_sensor.contact_kitchen_window_right_virtual:
  name: Правое Окно 

binary_sensor.contact_bedroom_window_left_virtual:
  name: Левое Окно

binary_sensor.contact_bedroom_window_right_virtual:
  name: Правое Окно

binary_sensor.contact_living_window_virtual:
  name: Окно
