binary_sensor.window_kitchen_left:
  name: Левое Окно

binary_sensor.window_kitchen_right:
  name: Правое Окно 

binary_sensor.window_bedroom_left:
  name: Левое Окно

binary_sensor.window_bedroom_right:
  name: Правое Окно

binary_sensor.window_living:
  name: Окно
