- platform: template
  switches:
    d_bath:
      value_template: '{{ is_state("binary_sensor.sw_toilet_fan", "on") }}'
      icon_template: '{{ iif(is_state("binary_sensor.sw_toilet_fan", "on"), "mdi:fan-alert", "mdi:fan") }}'
      turn_off: 
        service: script.h_toilet_off
      turn_on: 
        service: script.h_toilet_on