- platform: group
  name: sg_bedroom
  entities:
  - switch.bedroom_switch_left
  - switch.bedroom_switch_right

- platform: template
  switches:
    h_bedroom:
      value_template: '{{ is_state("binary_sensor.sw_bedroom_humidifier", "on") }}'
      icon_template: '{{ iif(is_state("binary_sensor.hydration_bedroom_humidifier_is_empty", "off"), "mdi:air-humidifier", "mdi:water-alert-outline") }}'
      turn_off: 
        service: script.h_bedroom_off
      turn_on: 
        service: script.h_bedroom_on