- platform: template
  switches:
    d_toilet:
      value_template: "{{ state_attr('binary_sensor.relay', 'toilet_1') }}"
      icon_template: "{{ iif(state_attr('binary_sensor.relay', 'toilet_1'), 'mdi:fan-alert', 'mdi:fan') }}"
      turn_off: 
        service: script.de_toilet_off
      turn_on: 
        service: script.de_toilet_on