- platform: template
  switches:
    h_hall:
      value_template: "{{ state_attr('binary_sensor.relay', 'hall_2') }}"
      icon_template: "{{ iif(state_attr('sensor.humidifier_empty', 'hall'), 'mdi:air-humidifier', 'mdi:water-alert-outline') }}"
      turn_off: 
        service: script.h_hall_off
      turn_on: 
        service: script.h_hall_on

    h_bedroom:
      value_template: "{{ state_attr('binary_sensor.relay', 'bedroom_2') }}"
      icon_template: "{{ iif(state_attr('sensor.humidifier_empty', 'bedroom'), 'mdi:air-humidifier', 'mdi:water-alert-outline') }}"
      turn_off: 
        service: script.h_bedroom_off
      turn_on: 
        service: script.h_bedroom_on

    h_living:
      value_template: "{{ state_attr('binary_sensor.relay', 'living_1') }}"
      icon_template: "{{ iif(state_attr('sensor.humidifier_empty', 'living'), 'mdi:air-humidifier', 'mdi:water-alert-outline') }}"
      turn_off: 
        service: script.h_living_off
      turn_on: 
        service: script.h_living_on
