- platform: group
  name: s_living
  entities:
  - switch.living_switch_left
  - switch.living_switch_right

- platform: template
  switches:
    h_living:
      value_template: '{{ is_state("binary_sensor.sw_living_humidifier", "on") }}'
      icon_template: '{{ iif(is_state("binary_sensor.hydration_living_humidifier_is_empty", "off"), "mdi:air-humidifier", "mdi:water-alert-outline") }}'
      turn_off: 
        service: script.h_living_off
      turn_on: 
        service: script.h_living_on