- platform: template
  switches:
    h_living:
      value_template: "{{ state_attr('sensor.relay', 'living_1') }}"
      icon_template: "{{ iif(state_attr('sensor.humidifier_empty', 'living'), 'mdi:air-humidifier', 'mdi:water-alert-outline') }}"
      turn_off: 
        service: script.h_living_off
      turn_on: 
        service: script.h_living_on
