- platform: template
  switches:
    living_switch:
      value_template: "{{ is_state('binary_sensor.switch_living_on', 'on') }}"
      turn_on:
      - service: switch.turn_on
        data:
          entity_id: switch.living_switch_left, switch.living_switch_right
      turn_off:
      - service: switch.turn_off
        data:
          entity_id: switch.living_switch_left, switch.living_switch_right
