## BACK LIGHT KITCHEN
- alias: 'back_light_kitchen'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_kitchen_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_kitchen_permission
        state: 'on'
      sequence:
      - service: script.back_light_kitchen_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_kitchen_permission
        state: 'off'
      sequence:
      - service: script.back_light_kitchen_off

## BACK LIGHT HALL
- alias: 'back_light_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_hall_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_hall_permission
        state: 'on'
      sequence:
      - service: script.back_light_hall_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_hall_permission
        state: 'off'
      sequence:
      - service: script.back_light_hall_off

## BACK LIGHT BEDROOM
- alias: 'back_light_bedroom_1'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_bedroom_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_bedroom_permission
        state: 'on'
      sequence:
      - service: script.back_light_bedroom_1_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_bedroom_permission
        state: 'off'
      sequence:
      - service: script.back_light_bedroom_1_off

- alias: 'back_light_bedroom_2'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_bedroom_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_bedroom_permission
        state: 'on'
      sequence:
      - service: script.back_light_bedroom_2_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_bedroom_permission
        state: 'off'
      sequence:
      - service: script.back_light_bedroom_2_off

## BACK LIGHT LIVING
- alias: 'back_light_living'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_living_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_living_permission
        state: 'on'
      sequence:
      - service: script.back_light_living_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_living_permission
        state: 'off'
      sequence:
      - service: script.back_light_living_off

## BACK LIGHT BALCONY
- alias: 'back_light_balcony'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.back_light_balcony_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_balcony_permission
        state: 'on'
      sequence:
      - service: script.back_light_balcony_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.back_light_balcony_permission
        state: 'off'
      sequence:
      - service: script.back_light_balcony_off
