## NIGHT LIGHT KITCHEN
- alias: 'night_light_kitchden'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.night_light_kitchen_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_kitchen_permission
        state: 'on'
      sequence:
      - service: script.night_light_kitchden_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_kitchen_permission
        state: 'off'
      sequence:
      - service: script.night_light_kitchden_off

## NIGHT LIGHT BATH
- alias: 'night_light_bath'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.night_light_bath_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_bath_permission
        state: 'on'
      sequence:
      - service: script.night_light_bath_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_bath_permission
        state: 'off'
      sequence:
      - service: script.night_light_bath_off

## NIGHT LIGHT TOILET
- alias: 'night_light_toilet'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.night_light_toilet_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_toilet_permission
        state: 'on'
      sequence:
      - service: script.night_light_toilet_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_toilet_permission
        state: 'off'
      sequence:
      - service: script.night_light_toilet_off

## NIGHT LIGHT HALL
- alias: 'night_light_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.night_light_hall_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_hall_permission
        state: 'on'
      sequence:
      - service: script.night_light_hall_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_hall_permission
        state: 'off'
      sequence:
      - service: script.night_light_hall_off

## NIGHT LIGHT BALCONY
- alias: 'night_light_balcony'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.night_light_balciony_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_balciony_permission
        state: 'on'
      sequence:
      - service: script.night_light_balcony_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_light_balciony_permission
        state: 'off'
      sequence:
      - service: script.night_light_balcony_off
