## OUTLET
- alias: 'outlet_balcony'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.outlet_balcony_permission'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.outlet_balcony_permission
        state: 'on'
      sequence:
      - service: script.outlet_balcony_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.outlet_balcony_permission
        state: 'off'
      sequence:
      - service: scoutlet_balcony_off
