## SWITCH KITCHEN
- alias: 'switch_kitchen_1'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.switch_kitchen_left_permission'
    to: 'on'
  action:
  - service: script.switch_kitchen_left_on

- alias: 'switch_kitchen_2'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.switch_kitchen_right_permission'
    to: 'on'
  action:
  - service: script.switch_kitchen_right_on

## SWITCH HALL
- alias: 'switch_hall'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.switch_hall_permission'
    to: 'on'
  action:
  - service: script.switch_hall_on

## SWITCH BEDROOM
- alias: 'switch_bedroom'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.switch_bedroom_permission'
    to: 'on'
  action:
  - service: script.switch_bedroom_on

## SWITCH LIVING
- alias: 'switch_living'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.switch_living_permission'
    to: 'on'
  action:
  - service: script.switch_living_on
