- platform: template
  lights:
    top_light_bath:
      value_template: "{{ is_state('switch.hall_switch_restroom_right', 'on') }}"
      turn_on:
        service: script.top_light_bath_on
      turn_off:
        service: script.top_light_bath_off

    night_light_bath:
      value_template: "{{ is_state('switch.bath_relay_l1', 'on') }}"
      turn_on:
        service: script.night_light_toilet_on
      turn_off:
        service: script.night_light_toilet_off
