- name: top_light_bedroom_1
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_1_host
  token: !secret bedroom_lamp_1_token
- name: top_light_bedroom_2
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_2_host
  token: !secret bedroom_lamp_2_token
- name: top_light_bedroom_3
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_3_host
  token: !secret bedroom_lamp_3_token
- name: top_light_bedroom_4
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_4_host
  token: !secret bedroom_lamp_4_token
- name: top_light_bedroom_5
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_5_host
  token: !secret bedroom_lamp_5_token
- name: top_light_bedroom_6
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret bedroom_lamp_6_host
  token: !secret bedroom_lamp_6_token
- platform: group
  name: top_light_bedroom_group
  entities:
  - light.top_light_bedroom_1
  - light.top_light_bedroom_2
  - light.top_light_bedroom_3
  - light.top_light_bedroom_4
  - light.top_light_bedroom_5
  - light.top_light_bedroom_6

- platform: template
  lights:
    back_light_bedroom:
      value_template: "{{ is_state('switch.bedroom_relay_l1', 'on') }}"
      turn_on:
        service: script.back_light_bedroom_1_on
      turn_off:
        service: script.back_light_bedroom_1_off

    wall_light_bedroom:
      value_template: "{{ is_state('switch.bedroom_wall_switch', 'on') }}"
      turn_on:
        service: script.back_light_bedroom_2_on
      turn_off:
        service: script.back_light_bedroom_2_off
