- name: top_light_hall_1
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret hall_lamp_1_host
  token: !secret hall_lamp_1_token
- name: top_light_hall_2
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret hall_lamp_2_host
  token: !secret hall_lamp_2_token
- name: top_light_hall_3
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret hall_lamp_3_host
  token: !secret hall_lamp_3_token
- name: top_light_hall_4
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret hall_lamp_4_host
  token: !secret hall_lamp_4_token
- name: top_light_hall_5
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret hall_lamp_5_host
  token: !secret hall_lamp_5_token
- name: top_light_hall_6
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret hall_lamp_6_host
  token: !secret hall_lamp_6_token
- platform: group
  name: top_light_hall_group
  entities:
  - light.top_light_hall_1
  - light.top_light_hall_2
  - light.top_light_hall_3
  - light.top_light_hall_4
  - light.top_light_hall_5
  - light.top_light_hall_6

- platform: template
  lights:
    back_light_hall:
      value_template: "{{ is_state('switch.hall_relay_l1', 'on') }}"
      turn_on:
        service: script.back_light_hall_on
      turn_off:
        service: script.back_light_hall_off
