- name: top_light_kitchen_1
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_1_host
  token: !secret kitchen_lamp_1_token
- name: top_light_kitchen_2
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_2_host
  token: !secret kitchen_lamp_2_token
- name: top_light_kitchen_3
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_3_host
  token: !secret kitchen_lamp_3_token
- name: top_light_kitchen_4
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_4_host
  token: !secret kitchen_lamp_4_token
- name: top_light_kitchen_5
  platform: xiaomi_miio_philipslight
  model: philips.light.downlight
  host: !secret kitchen_lamp_5_host
  token: !secret kitchen_lamp_5_token
- platform: group
  name: top_light_kitchen_group
  entities:
  - light.top_light_kitchen_1
  - light.top_light_kitchen_2
  - light.top_light_kitchen_3
  - light.top_light_kitchen_4
  - light.top_light_kitchen_5

- platform: template
  lights:
    back_light_kitchen:
      value_template: "{{ states('switch.kitchen_relay_l2') }}"
      turn_on:
        service: script.back_light_kitchen_on
      turn_off:
        service: script.back_light_kitchen_off

    night_light_kitchen:
      value_template: "{{ states('switch.kitchen_relay_l1') }}"
      turn_on:
        service: script.night_light_kitchden_on
      turn_off:
        service: script.night_light_kitchden_off
