- platform: template
  lights:
    top_light_toilet:
      value_template: "{{ states('switch.hall_switch_restroom_left') }}"
      turn_on:
        service: script.top_light_toilet_on
      turn_off:
        service: script.top_light_toilet_off

    night_light_toilet:
      value_template: "{{ states('switch.toilet_relay_l2') }}"
      turn_on:
        service: script.night_light_toilet_on
      turn_off:
        service: script.night_light_toilet_off
