## ILLUMINANCE SENSORS
- platform: history_stats
  name: illuminance_max_level
  entity_id: sensor.illuminance_level
  state: 'on'
  type: max
  end: '{{ now().strftime("%Y-%m-%d 23:59:59") }}'
  duration:
    days: 1