## ILLUMINANCE SENSORS
- platform: history_stats
  name: illuminance_max_level
  entity_id: sensor.illuminance_level
  state: 'max'
  type: 'time'
  start: '{{ now().replace(hour=0, minute=0, second=0, microsecond=0 ) }}'
  end: '{{ now().replace(hour=23, minute=59, second=59, microsecond=0 ) }}'