## ILLUMINANCE SENSORS
- platform: history_stats
  name: illuminance_max_level
  entity_id: sensor.illuminance_level
  state: 'max'
  type: 'time'
  end: '{{ now().strftime("%Y-%m-%d") }}'
  duration:
    hours: 24
