## BUTTON BEDROOM
- alias: 'button_bedroom_left_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state 
    entity_id: sensor.bedroom_wall_switch_action
    to: 'single'
  - platform: state 
    entity_id: sensor.bedroom_switch_action
    to: 'single_left'
  action:
  - service: script.button_bedroom_left_toggle


- alias: 'button_bedroom_right_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state 
    entity_id: sensor.bedroom_switch_action
    to: 'single_right'
  action:
  - service: script.button_bedroom_right_toggle


- alias: 'button_bedroom_both_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state 
    entity_id: sensor.bedroom_switch_action
    to: 'single_both'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_mode_bedroom_boolean
        state: 'off'
      sequence:
      - delay: "{{ state_attr('sensor.delay', 'night_mode_on') }}"
      - service: script.button_bedroom_both_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_mode_bedroom_boolean
        state: 'on'
      sequence:
      - service: script.button_bedroom_both_off
