## BUTTON HALL
- alias: 'button_hall_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.hall_switch_action
    to: 'single'
  action:
  - service: script.button_hall_toggle

- alias: 'button_hall_both_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.button_hall_both_toggle
    to: 'single_both'
  action:
  - service: script.button_hall_both_toggle