# BUTTON LITCHEN
- alias: 'button_kitchen_left_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.kitchen_switch_action
    to: 'single_left'
  action:
  - service: script.button_kitchen_left_toggle

- alias: 'button_kitchen_right_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.kitchen_switch_action
    to: 'single_right'
  action:
  - service: script.button_kitchen_right_toggle

- alias: 'button_kitchen_both_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.kitchen_switch_action
    to: 'single_both'
  action:
  - service: script.button_kitchen_both_toggle
