## BUTTON LIVING
- alias: 'button_living_left_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.living_switch_action
    to: 'single_left'
  action:
  - service: script.button_living_left_toggle


- alias: 'button_living_right_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: sensor.living_switch_action
    to: 'single_right'
  action:
  - service: script.button_living_right_toggle


- alias: 'button_living_both_toggle'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state 
    entity_id: sensor.living_switch_action
    to: 'single_both'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_mode_living_boolean
        state: 'off'
      sequence:
      - delay: "{{ state_attr('sensor.delay', 'night_mode_on') }}"
      - service: script.button_living_both_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.night_mode_living_boolean
        state: 'on'
      sequence:
      - service: script.button_living_both_off
