## BUTTON TOILET
- alias: 'button_toilet_toggle'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hall_switch_restroom_action
    to: 'single_right'
  action:
  - service: script.button_toilet_toggle

- alias: 'button_toilet_long_toggle'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.toilet_button_action
    to: 'hold'
  - platform: state
    entity_id: sensor.bath_button_action
    to: 'hold'
  action:
  - service: script.button_toilet_long_toggle
