## HALL
- alias: 'd_hall_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'hall'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'hall'
    from: true
    to: false
  action:
  - service: script.d_hall_timer_cancel
  - service: script.d_hall_timer_start

- alias: 'd_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_hall
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'hall'
    state: true
  action:
  - service: script.d_hall_boolean_on

- alias: 'd_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_hall
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'hall'
    state: false
  action:
  - service: script.d_hall_boolean_off


## TOILET
- alias: 'd_toilet_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet'
    from: true
    to: false
  action:
  - service: script.d_toilet_timer_cancel
  - service: script.d_toilet_timer_start

- alias: 'd_toilet_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_toilet
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet'
    state: true
  action:
  - service: script.d_toilet_boolean_on

- alias: 'd_toilet_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_toilet
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet'
    state: false
  action:
  - service: script.d_toilet_boolean_off


## BEDROOM
- alias: 'd_bedroom_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'bedroom'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'bedroom'
    from: true
    to: false
  action:
  - service: script.d_bedroom_timer_cancel
  - service: script.d_bedroom_timer_start

- alias: 'd_bedroom_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_bedroom
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'bedroom'
    state: true
  action:
  - service: script.d_bedroom_boolean_on

- alias: 'd_bedroom_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_bedroom
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'bedroom'
    state: false
  action:
  - service: script.d_bedroom_boolean_off


## LIVING
- alias: 'd_living_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'living'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'living'
    from: true
    to: false
  action:
  - service: script.d_living_timer_cancel
  - service: script.d_living_timer_start

- alias: 'd_living_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_living
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'living'
    state: true
  action:
  - service: script.d_living_boolean_on

- alias: 'd_living_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_living
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'living'
    state: false
  action:
  - service: script.d_living_boolean_off


## BALCONY
- alias: 'd_balcony_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'balcony'
    from: false
    to: true
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'balcony'
    from: true
    to: false
  action:
  - service: script.d_balcony_timer_cancel
  - service: script.d_balcony_timer_start

- alias: 'd_balcony_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_balcony
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'balcony'
    state: true
  action:
  - service: script.d_balcony_boolean_on

- alias: 'd_balcony_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.d_balcony
  condition:
  - condition: state
    entity_id: 'binary_sensor.door'
    attribute: 'balcony'
    state: false
  action:
  - service: script.d_balcony_boolean_off
