## ILLUMINANCE
- alias: 'i_level_set_number'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'illuminance_sensor'
  action:
  - service: script.i_level_set_number

