## ELEVATION
- alias: 's_elevation_set_number'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.cloud'
    attribute: 'cloud_sensor'
  action:
  - service: script.s_elevation_set_number


## AZIMUTH
- alias: 's_azimuth_set_number'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.cloud'
    attribute: 'cloud_sensor'
  action:
  - service: script.s_azimuth_set_number


