binary_sensor.occupancy_kitchen:
  name: Occupancy

binary_sensor.occupancy_bath:
  name: Occupancy

binary_sensor.occupancy_toilet:
  name: Occupancy

binary_sensor.occupancy_hall:
  name: Occupancy
