## CLOUD
- alias: 'c_state'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.c_state'
    for: '00:00:10'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.c_state
        state: 'on'
      sequence:
      - service: script.on_c_state
    - conditions:
      - condition: state
        entity_id: binary_sensor.c_state
        state: 'off'
      sequence:
      - service: script.off_c_state
