## CLOUDLY
- alias: 'c_cloudly_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.cloud'
    attribute: 'cloud_sensor'
  condition:
  - condition: state
    entity_id: 'sensor.cloud'
    attribute: 'cloud_state'
    state: true
  action:
  - service: script.c_cloudly_boolean_on

- alias: 'c_cloudly_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.cloud'
    attribute: 'cloud_sensor'
  condition:
  - condition: state
    entity_id: 'sensor.cloud'
    attribute: 'cloud_state'
    state: false
  action:
  - service: script.c_cloudly_boolean_off



