- alias: 'c_cloudly_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.cloud'
    from: 'off'
    to: 'on'
  action:
  - service: script.c_cloudly_on

- alias: 'c_cloudly_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.cloud'
    from: 'on'
    to: 'off'
  action:
  - service: script.c_cloudly_off


