## CLOUD
- alias: 'c_cloudly_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.cloud-state'
    to: 'on'
  action:
  - service: script.c_cloudly_boolean_on

- alias: 'c_cloudly_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.cloud-state'
    to: 'off'
  action:
  - service: script.c_cloudly_boolean_off
