## CLOUD
- alias: 'on_c_state'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.c_state'
    to: 'on'
  action:
  - service: script.on_c_state

- alias: 'off_c_state'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.c_state'
    to: 'off'
  action:
  - service: script.off_c_state
