## KITCHEN
- alias: 'c_kitchen_position_set_number'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.curtain'
    attribute: 'kitchen_state'
  action:
  - service: script.c_kitchen_position_set_number


## BEDROOM
- alias: 'c_bedroom_position_set_number'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.curtain'
    attribute: 'bedroom_state'
  action:
  - service: script.c_bedroom_position_set_number


## LIVING
- alias: 'c_living_position_set_number'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.curtain'
    attribute: 'living_state'
  action:
  - service: script.c_living_position_set_number
