## BATH
- alias: 'de_bath_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehudration'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.de_bath_boolean_on

- alias: 'de_bath_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehudration'
    attribute: 'bath'
    from: 'on'
    to: 'off'
  action:
  - service: script.de_bath_boolean_off


## TOILET
- alias: 'de_toilet_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehudration'
    attribute: 'toilet'
    from: 'off'
    to: 'on'
  action:
  - service: script.de_toilet_boolean_on

- alias: 'de_toilet_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehudration'
    attribute: 'toilet'
    from: 'on'
    to: 'off'
  action:
  - service: script.de_toilet_boolean_off
