## BATH
- alias: 'de_bath_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehumidifier'
    attribute: 'bath_state'
    from: false
    to: true
  action:
  - service: script.de_bath_boolean_on

- alias: 'de_bath_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehumidifier'
    attribute: 'bath_state'
    from: true
    to: false
  action:
  - service: script.de_bath_boolean_off


## TOILET
- alias: 'de_toilet_timer_start'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet_boolean'
    from: false
    to: true
  action:
  - service: script.de_toilet_timer_start

- alias: 'de_toilet_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet_boolean'
    from: false
    to: true
  action:
  - service: script.de_toilet_boolean_on

- alias: 'de_toilet_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.de_toilet
  action:
  - service: script.de_toilet_boolean_off



