## DEHUMIDIFIER BATH
- alias: 'dehumidifier_bath_on'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidity_bath_hight'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bath_hight
        state: 'on'
      sequence:
      - service: script.button_toilet_long_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bath_hight
        state: 'off'
      sequence:
      - service: script.button_toilet_long_off

## DEHUMIDIFIER TOILET
- alias: 'dehumidifier_toilet_on'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_toilet_open'
    to: 'on'
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy_toilet_boolean'
    state: 'on'
  - condition: state
    entity_id: 'binary_sensor.humidity_bath_hight'
    state: 'off'
  action:
  - service: script.button_toilet_long_on
  - service: script.dehumidifier_toilet_timer_start
  
- alias: 'dehumidifier_toilet_off'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dehumidifier_toilet
  condition:
  - condition: state
    entity_id: 'binary_sensor.humidity_bath_hight'
    state: 'off'
  action:
  - service: script.button_toilet_long_off

- alias: 'dehumidifier_toilet_timer_cancel'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.dehumidifier_toilet_on'
    to: 'off'
  - platform: state
    entity_id: 'binary_sensor.humidity_bath_hight'
    to: 'on'
  action:
  - service: script.dehumidifier_toilet_timer_cancel
