## HALL
- alias: 'd_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'hall_sensor'
    from: false
    to: true
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_hall_boolean_on

- alias: 'd_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'hall_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_hall_boolean_off


## TOILET
- alias: 'd_toilet_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet_sensor'
    from: false
    to: true
  action:
  - service: script.d_toilet_boolean_on

- alias: 'd_toilet_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet_sensor'
    from: true
    to: false
  action:
  - service: script.d_toilet_boolean_off


## BEDROOM
- alias: 'd_bedroom_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'bedroom_sensor'
    from: false
    to: true
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_bedroom_boolean_on

- alias: 'd_bedroom_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'bedroom_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_bedroom_boolean_off


## LIVING
- alias: 'd_living_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'living_sensor'
    from: false
    to: true
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_living_boolean_on

- alias: 'd_living_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'living_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_living_boolean_off


## BALCONY
- alias: 'd_balcony_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'balcony_sensor'
    from: false
    to: true
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_balcony_boolean_on

- alias: 'd_balcony_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'balcony_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'door') }}"
  action:
  - service: script.d_balcony_boolean_off
