## HUMIDIFIER EMPTY HALL
- alias: 'humidifier_hall_empty_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_hall_empty'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'power_on') }}"
  action:
  - service: script.humidifier_hall_empty_on

- alias: 'humidifier_hall_empty_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_hall_empty'
    to: 'off'
  action:
  - service: script.humidifier_hall_empty_off


## HUMIDIFIER EMPTY BEDROOM
- alias: 'humidifier_bedroom_empty_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_bedroom_empty'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'power_on') }}"
  action:
  - service: script.humidifier_bedroom_empty_on

- alias: 'humidifier_bedroom_empty_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_bedroom_empty'
    to: 'off'
  action:
  - service: script.humidifier_bedroom_empty_off


## HUMIDIFIER EMPTY LIVING
- alias: 'hhumidifier_living_empty_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_living_empty'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'power_on') }}"
  action:
  - service: script.humidifier_living_empty_on

- alias: 'hhumidifier_living_empty_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.humidifier_living_empty'
    to: 'off'
  action:
  - service: script.humidifier_living_empty_off
