## ILLUMINANCE CURTAIN KITCHEN
- alias: 'illuminance_kitchen_curtain'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_kitchen_curtain'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_kitchen_curtain'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_kitchen_curtain
        state: 'on'
      sequence:
      - service: script.illuminance_kitchen_curtain_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_kitchen_curtain
        state: 'off'
      sequence:
      - service: script.illuminance_kitchen_curtain_off

## ILLUMINANCE CURTAIN BEDROOM
- alias: 'illuminance_bedroom_curtain'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_bedroom_curtain'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_bedroom_curtain'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_bedroom_curtain
        state: 'on'
      sequence:
      - service: script.illuminance_bedroom_curtain_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_bedroom_curtain
        state: 'off'
      sequence:
      - service: script.illuminance_bedroom_curtain_off

## ILLUMINANCE CURTAIN LIVING
- alias: 'illuminance_living_curtain'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_living_curtain'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_living_curtain'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_living_curtain
        state: 'on'
      sequence:
      - service: script.illuminance_living_curtain_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_living_curtain
        state: 'off'
      sequence:
      - service: script.illuminance_living_curtain_off

## ILLUMINANCE TOP LIGHT KITCHEN
- alias: 'illuminance_kitchen_top_light'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_kitchen_top_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_kitchen_top_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_kitchen_top_light
        state: 'on'
      sequence:
      - service: script.illuminance_kitchen_top_light_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_kitchen_top_light
        state: 'off'
      sequence:
      - service: script.illuminance_kitchen_top_light_off

## ILLUMINANCE TOP LIGHT HALL
- alias: 'illuminance_hall_top_light'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_hall_top_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_hall_top_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_hall_top_light
        state: 'on'
      sequence:
      - service: script.illuminance_hall_top_light_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_hall_top_light
        state: 'off'
      sequence:
      - service: script.illuminance_hall_top_light_off

## ILLUMINANCE BACK LIGHT KITCHEN
- alias: 'illuminance_kitchen_back_light'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_kitchen_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_kitchen_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_kitchen_back_light
        state: 'on'
      sequence:
      - service: script.illuminance_kitchen_back_light_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_kitchen_back_light
        state: 'off'
      sequence:
      - service: script.illuminance_kitchen_back_light_off

## ILLUMINANCE BACK LIGHT HALL
- alias: 'illuminance_hall_back_light'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_hall_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_hall_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_hall_back_light
        state: 'on'
      sequence:
      - service: script.illuminance_hall_back_light_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_hall_back_light
        state: 'off'
      sequence:
      - service: script.illuminance_hall_back_light_off

## ILLUMINANCE BACK LIGHT BEDROOM
- alias: 'illuminance_bedroom_back_light'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_bedroom_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_bedroom_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_bedroom_back_light
        state: 'on'
      sequence:
      - service: script.illuminance_bedroom_back_light_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_bedroom_back_light
        state: 'off'
      sequence:
      - service: script.illuminance_bedroom_back_light_off

## ILLUMINANCE BACK LIGHT LIVING
- alias: 'illuminance_living_back_light'
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.illuminance_living_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_on') }}"
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.illuminance_living_back_light'
    for: "{{ state_attr('sensor.delay', 'illuminance_off') }}"
    to: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_living_back_light
        state: 'on'
      sequence:
      - service: script.illuminance_living_back_light_on
    - conditions:
      - condition: state
        entity_id: binary_sensor.illuminance_living_back_light
        state: 'off'
      sequence:
      - service: script.illuminance_living_back_light_off
