## KITCHEN TOP LIGTH
- alias: 'i_kitchen_top_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_top_light_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_top_light_state'
    from: true
    to: false
  action:
  - service: script.i_kitchen_top_light_timer_cancel
  - service: script.i_kitchen_top_light_timer_start

- alias: 'i_kitchen_top_light_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_kitchen_top_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_top_light_state'
    state: true
  action:
  - service: script.i_kitchen_top_light_boolean_on

- alias: 'i_kitchen_top_light_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_kitchen_top_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_top_light_state'
    state: false
  action:
  - service: script.i_kitchen_top_light_boolean_off


## KITCHEN BACK LIGTH
- alias: 'i_kitchen_back_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_back_light_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_back_light_state'
    from: true
    to: false
  action:
  - service: script.i_kitchen_back_light_timer_cancel
  - service: script.i_kitchen_back_light_timer_start

- alias: 'i_kitchen_back_light_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_kitchen_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_back_light_state'
    state: true
  action:
  - service: script.i_kitchen_back_light_boolean_on

- alias: 'i_kitchen_back_light_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_kitchen_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_back_light_state'
    state: false
  action:
  - service: script.i_kitchen_back_light_boolean_off

## KITCHEN CURTAIN
- alias: 'i_kitchen_curtain_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_curtain_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_curtain_state'
    from: true
    to: false
  action:
  - service: script.i_kitchen_curtain_timer_cancel
  - service: script.i_kitchen_curtain_timer_start

- alias: 'i_kitchen_curtain_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_kitchen_curtain
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_curtain_state'
    state: true
  action:
  - service: script.i_kitchen_curtain_boolean_on

- alias: 'i_kitchen_curtain_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_kitchen_curtain
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'kitchen_curtain_state'
    state: false
  action:
  - service: script.i_kitchen_curtain_boolean_off


## HALL TOP LIGTH
- alias: 'i_hall_top_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_top_light_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_top_light_state'
    from: true
    to: false
  action:
  - service: script.i_hall_top_light_timer_cancel
  - service: script.i_hall_top_light_timer_start

- alias: 'i_hall_top_light_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_hall_top_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_top_light_state'
    state: true
  action:
  - service: script.i_hall_top_light_boolean_on

- alias: 'i_hall_top_light_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_hall_top_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_top_light_state'
    state: false
  action:
  - service: script.i_hall_top_light_boolean_off

## HALL BACK LIGTH
- alias: 'i_hall_back_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_back_light_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_back_light_state'
    from: true
    to: false
  action:
  - service: script.i_hall_back_light_timer_cancel
  - service: script.i_hall_back_light_timer_start

- alias: 'i_hall_back_light_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_hall_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_back_light_state'
    state: true
  action:
  - service: script.i_hall_back_light_boolean_on

- alias: 'i_hall_back_light_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_hall_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'hall_back_light_state'
    state: false
  action:
  - service: script.i_hall_back_light_boolean_off


## BEDROOM BACK LIGTH
- alias: 'i_bedroom_back_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_back_light_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_back_light_state'
    from: true
    to: false
  action:
  - service: script.i_bedroom_back_light_timer_cancel
  - service: script.i_bedroom_back_light_timer_start

- alias: 'i_bedroom_back_light_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_bedroom_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_back_light_state'
    state: true
  action:
  - service: script.i_bedroom_back_light_boolean_on

- alias: 'i_bedroom_back_light_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_bedroom_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_back_light_state'
    state: false
  action:
  - service: script.i_bedroom_back_light_boolean_off


## BEDROOM CURTAIN
- alias: 'i_bedroom_curtain_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_curtain_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_curtain_state'
    from: true
    to: false
  action:
  - service: script.i_bedroom_curtain_timer_cancel
  - service: script.i_bedroom_curtain_timer_start

- alias: 'i_bedroom_curtain_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_bedroom_curtain
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_curtain_state'
    state: true
  action:
  - service: script.i_bedroom_curtain_boolean_on

- alias: 'i_bedroom_curtain_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_bedroom_curtain
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'bedroom_curtain_state'
    state: false
  action:
  - service: script.i_bedroom_curtain_boolean_off


## LIVING BACK LIGTH
- alias: 'i_living_back_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_back_light_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_back_light_state'
    from: true
    to: false
  action:
  - service: script.i_living_back_light_timer_cancel
  - service: script.i_living_back_light_timer_start

- alias: 'i_living_back_light_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_living_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_back_light_state'
    state: true
  action:
  - service: script.i_living_back_light_boolean_on

- alias: 'i_living_back_light_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_living_back_light
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_back_light_state'
    state: false
  action:
  - service: script.i_living_back_light_boolean_off

## LIVING CURTAIN
- alias: 'i_living_curtain_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_curtain_state'
    from: false
    to: true
  - platform: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_curtain_state'
    from: true
    to: false
  action:
  - service: script.i_living_curtain_timer_timer_cancel
  - service: script.i_living_curtain_timer_timer_start

- alias: 'i_living_curtain_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_living_curtain
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_curtain_state'
    state: true
  action:
  - service: script.i_living_curtain_boolean_on

- alias: 'i_living_curtain_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.i_living_curtain
  condition:
  - condition: state
    entity_id: 'sensor.illuminance'
    attribute: 'living_curtain_state'
    state: false
  action:
  - service: script.i_living_curtain_boolean_off
