## NORMAL
- alias: 'n_normal_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.network'
    attribute: 'normal_state'
    from: false
    to: true
  action:
  - service: script.n_normal_boolean_on

- alias: 'n_normal_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.network'
    attribute: 'normal_state'
    from: true
    to: false
  action:
  - service: script.n_normal_boolean_off
