## NIGHT MODE 
- alias: 'night_mode_auto_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.night_mode_auto_on'
  action:
  - service: script.button_bedroom_both_on
  - service: script.button_living_both_on

- alias: 'night_mode_auto_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: event
    event_type: state_changed
    entity_id: 'binary_sensor.night_mode_auto_off'
  action:
  - service: script.button_bedroom_both_off
  - service: script.button_living_both_off
