## HALL
- alias: 'nm_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'input_boolean.dt_night'
    from: 'off'
    to: 'on'
  action:
  - service: script.nm_hall_boolean_on

- alias: 'nm_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'input_boolean.dt_night'
    from: 'on'
    to: 'off'
  action:
  - service: script.nm_hall_boolean_off


## BEDROOM
- alias: 'nm_bedroom_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'input_boolean.dt_night'
    from: 'off'
    to: 'on'
  action:
  - service: script.nm_bedroom_boolean_on

- alias: 'nm_bedroom_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'input_boolean.dt_night'
    from: 'on'
    to: 'off'
  action:
  - service: script.nm_bedroom_boolean_off


## LIVING
- alias: 'nm_living_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'input_boolean.dt_night'
    from: 'off'
    to: 'on'
  action:
  - service: script.nm_living_boolean_on

- alias: 'nm_living_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'input_boolean.dt_night'
    from: 'on'
    to: 'off'
  action:
  - service: script.nm_living_boolean_off
