## KITCHEN
- alias: 'o_kitchen_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.o_kitchen_on

- alias: 'o_kitchen_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.o_kitchen
  action:
  - service: script.o_kitchen_off

- alias: 'o_kitchen_timer_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'on'
    to: 'off'
  action:
  - service: script.o_kitchen_start

- alias: 'o_kitchen_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.o_kitchen_cancel

## HALL
- alias: 'o_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.o_hall_on

- alias: 'o_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.o_hall
  action:
  - service: script.o_hall_off

- alias: 'o_hall_timer_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'on'
    to: 'off'
  action:
  - service: script.o_hall_start

- alias: 'o_hall_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.o_hall_cancel

## BATH
- alias: 'o_bath_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.o_bath_on

- alias: 'o_bath_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.o_bath
  action:
  - service: script.o_bath_off

- alias: 'o_bath_timer_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'on'
    to: 'off'
  action:
  - service: script.o_bath_start

- alias: 'o_bath_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion'
    attribute: 'bath'
    from: 'off'
    to: 'on'
  action:
  - service: script.o_bath_cancel


