## KITCHEN
- alias: 'o_kitchen_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'kitchen_sensor'
    from: false
    to: true
  action:
  - service: script.o_kitchen_boolean_on

- alias: 'o_kitchen_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'kitchen_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'occupation') }}"
  action:
  - service: script.o_kitchen_boolean_off


## HALL
- alias: 'o_hall_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'hall_sensor'
    from: false
    to: true
  action:
  - service: script.o_hall_boolean_on

- alias: 'o_hall_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'hall_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'occupation') }}"
  action:
  - service: script.o_hall_boolean_off


## BATH
- alias: 'o_bath_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'bath_sensor'
    from: false
    to: true
  action:
  - service: script.o_bath_boolean_on

- alias: 'o_bath_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'bath_sensor'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'occupation') }}"
  action:
  - service: script.o_bath_boolean_off


## TOILET
- alias: 'o_toilet_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet_boolean'
    from: false
    to: true
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet_boolean'
    state: false
  action:
  - service: script.o_toilet_timer_start

- alias: 'o_toilet_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet_boolean'
    from: true
    to: false
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet_boolean'
    state: true
  - condition: state
    entity_id: 'timer.o_toilet'
    state: 'active'
  action:
  - service: script.o_toilet_timer_cancel

- alias: 'o_toilet_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet_boolean'
    from: false
    to: true
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet_boolean'
    state: false
  action:
  - service: script.o_toilet_boolean_on

- alias: 'o_toilet_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door'
    attribute: 'toilet_boolean'
    from: true
    to: false
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet_boolean'
    state: true
  - condition: state
    entity_id: 'timer.o_toilet'
    state: 'idle'
  action:
  - service: script.o_toilet_boolean_off
