## MOTION KITCHEN
- alias: 'motion_kitchen_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_kitchen'
    to: 'on'
  action:
  - service: script.motion_kitchen_on

- alias: 'motion_kitchen_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_kitchen'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'motion_off') }}"
  action:
  - service: script.motion_kitchen_off


## MOTION BATH
- alias: 'motion_bath_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_bath'
    to: 'on'
  action:
  - service: script.motion_bath_on

- alias: 'motion_bath_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_bath'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'motion_off') }}"
  action:
  - service: script.motion_bath_off


## MOTION HALL
- alias: 'motion_hall_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_hall'
    to: 'on'
  action:
  - service: script.motion_hall_on

- alias: 'motion_hall_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.motion_hall'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'motion_off') }}"
  action:
  - service: script.motion_hall_off


## OCCUPANCY TOILET
- alias: 'occupancy_toilet_timer_start'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_toilet_open'
    to: 'on'
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy_toilet_boolean'
    state: 'off'
  action:
  - service: script.occupancy_toilet_timer_start

- alias: 'occupancy_toilet_timer_cancel'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_toilet_open'
    to: 'off'
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy_toilet_boolean'
    state: 'on'
  - condition: state
    entity_id: 'timer.toilet_mode'
    state: 'active'
  action:
  - service: script.occupancy_toilet_timer_cancel

- alias: 'occupancy_toilet_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_toilet_open'
    to: 'on'
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy_toilet_boolean'
    state: 'off'
  action:
  - service: script.occupancy_toilet_on

- alias: 'occupancy_toilet_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_toilet_open'
    to: 'off'
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy_toilet_boolean'
    state: 'on'
  - condition: state
    entity_id: 'timer.toilet_mode'
    state: 'idle'
  action:
  - service: script.occupancy_toilet_off
