## HIGHT
- alias: 'p_hight_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'hight_state'
    from: false
    to: true
  action:
  - service: script.p_hight_boolean_on

- alias: 'p_hight_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'hight_state'
    from: true
    to: false
  action:
  - service: script.p_hight_boolean_off


## LOW
- alias: 'p_low_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'low_state'
    from: false
    to: true
  action:
  - service: script.p_low_boolean_on

- alias: 'p_low_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'low_state'
    from: true
    to: false
  action:
  - service: script.p_low_boolean_off
