## HIGHT
- alias: 'p_hight_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'hight_state'
    from: 'off'
    to: 'on'
  action:
  - service: script.p_hight_boolean_on

- alias: 'p_hight_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'hight_state'
    from: 'on'
    to: 'off'
  action:
  - service: script.p_hight_boolean_off


## LOW
- alias: 'p_low_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'low_state'
    from: 'off'
    to: 'on'
  action:
  - service: script.p_low_boolean_on

- alias: 'p_low_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'low_state'
    from: 'on'
    to: 'off'
  action:
  - service: script.p_low_boolean_off
