## HIGHT
- alias: 't_hight_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.temperature'
    attribute: 'hight_state'
    from: false
    to: true
  action:
  - service: script.t_hight_boolean_on

- alias: 't_hight_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.temperature'
    attribute: 'hight_state'
    from: true
    to: false
  action:
  - service: script.t_hight_boolean_off


## LOW
- alias: 't_low_boolean_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.temperature'
    attribute: 'low_state'
    from: false
    to: true
  action:
  - service: script.t_low_boolean_on

- alias: 't_low_boolean_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'sensor.temperature'
    attribute: 'low_state'
    from: true
    to: false
  action:
  - service: script.t_low_boolean_off
