## VENTILATION KITCHEN
- alias: 'ventilation_kitchen_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_kitchen'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_kitchen_on

- alias: 'ventilation_kitchen_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_kitchen'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_kitchen_off


## VENTILATION HALL
- alias: 'ventilation_hall_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_hall'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_hall_on

- alias: 'ventilation_hall_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_hall'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_hall_off


## VENTILATION BEDROOM
- alias: 'ventilation_bedroom_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_bedroom_on'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_bedroom_on

- alias: 'ventilation_bedroom_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_bedroom_on'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_bedroom_off


## VENTILATION LIVING
- alias: 'ventilation_living_on'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_living'
    to: 'on'
    for: "{{ state_attr('sensor.delay', 'ventilation_on') }}"
  action:
  - service: script.ventilation_living_on

- alias: 'ventilation_living_off'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.ventilation_living'
    to: 'off'
    for: "{{ state_attr('sensor.delay', 'ventilation_off') }}"
  action:
  - service: script.ventilation_living_off
