## KITCHEN LEFT
- alias: 'w_kitchen_left_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_left_sensor'
    to: true
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_left_sensor'
    to: false
  action:
  - service: script.w_kitchen_left_timer_cancel
  - service: script.w_kitchen_left_timer_start

- alias: 'w_kitchen_left_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_kitchen_left
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_left_sensor'
    state: true
  action:
  - service: script.w_kitchen_left_boolean_on

- alias: 'w_kitchen_left_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_kitchen_left
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_left_sensor'
    state: false
  action:
  - service: script.w_kitchen_left_boolean_off


## KITCHEN RIGHT
- alias: 'w_kitchen_right_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_right_sensor'
    to: true
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_right_sensor'
    to: false
  action:
  - service: script.w_kitchen_right_timer_cancel
  - service: script.w_kitchen_right_timer_start

- alias: 'w_kitchen_right_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_kitchen_right
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_right_sensor'
    state: true
  action:
  - service: script.w_kitchen_right_boolean_on

- alias: 'w_kitchen_right_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_kitchen_right
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'kitchen_right_sensor'
    state: false
  action:
  - service: script.w_kitchen_right_boolean_off


## BEDROOM LEFT
- alias: 'w_bedroom_left_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_left_sensor'
    to: true
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_left_sensor'
    to: false
  action:
  - service: script.w_bedroom_left_timer_cancel
  - service: script.w_bedroom_left_timer_start

- alias: 'w_bedroom_left_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_bedroom_left
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_left_sensor'
    state: true
  action:
  - service: script.w_bedroom_left_boolean_on

- alias: 'w_bedroom_left_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_bedroom_left
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_left_sensor'
    state: false
  action:
  - service: script.w_bedroom_left_boolean_off


## BEDROOM RIGHT
- alias: 'w_bedroom_right_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_right_sensor'
    to: true
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_right_sensor'
    to: false
  action:
  - service: script.w_bedroom_right_timer_cancel
  - service: script.w_bedroom_right_timer_start

- alias: 'w_bedroom_right_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_bedroom_right
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_right_sensor'
    state: true
  action:
  - service: script.w_bedroom_right_boolean_on

- alias: 'w_bedroom_right_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_bedroom_right
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'bedroom_right_sensor'
    state: false
  action:
  - service: script.w_bedroom_right_boolean_off


## LIVING
- alias: 'w_living_timer_action'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'living_sensor'
    to: true
  - platform: state
    entity_id: 'binary_sensor.window'
    attribute: 'living_sensor'
    to: false
  action:
  - service: script.w_living_timer_cancel
  - service: script.w_living_timer_start

- alias: 'w_living_boolean_on'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_living
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'living_sensor'
    state: true
  action:
  - service: script.w_living_boolean_on

- alias: 'w_living_boolean_off'
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.w_living
  condition:
  - condition: state
    entity_id: 'binary_sensor.window'
    attribute: 'living_sensor'
    state: false
  action:
  - service: script.w_living_boolean_off
