## CLOUD
- alias: 'set_c_level'
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'sensor.c_level'
  action:
  - service: script.set_c_level

- alias: 'set_c_state'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.c_state'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.c_state
        state: 'on'
      sequence:
      - service: script.on_c_state
    - conditions:
      - condition: state
        entity_id: binary_sensor.c_state
        state: 'off'
      sequence:
      - service: script.off_c_state
