## HUMIDITY
### BATH
- alias: 'humidity_bath'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.humidity_bath'
    attribute: 'normal'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bath
        attribute: 'hight'
        state: true
      sequence:
      - service: script.humidity_bath_hight_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bath
        attribute: 'low'
        state: true
      sequence:
      - service: script.humidity_bath_low_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bath
        attribute: 'normal'
        state: true 
      sequence:
      - service: script.humidity_bath_normal_message

### HALL
- alias: 'humidity_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.humidity_hall'
    attribute: 'normal'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_hall
        attribute: 'hight'
        state: true
      sequence:
      - service: script.humidity_hall_hight_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_hall
        attribute: 'low'
        state: true
      sequence:
      - service: script.humidity_hall_low_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_hall
        attribute: 'normal'
        state: true 
      sequence:
      - service: script.humidity_hall_normal_message

### BEDROOM
- alias: 'humidity_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.humidity_bedroom'
    attribute: 'normal'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bedroom
        attribute: 'hight'
        state: true
      sequence:
      - service: script.humidity_bedroom_hight_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bedroom
        attribute: 'low'
        state: true
      sequence:
      - service: script.humidity_bedroom_low_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_bedroom
        attribute: 'normal'
        state: true 
      sequence:
      - service: script.humidity_bedroom_normal_message

### LIVING
- alias: 'humidity_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.humidity_living'
    attribute: 'normal'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_living
        attribute: 'hight'
        state: true
      sequence:
      - service: script.humidity_living_hight_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_living
        attribute: 'low'
        state: true
      sequence:
      - service: script.humidity_living_low_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.humidity_living
        attribute: 'normal'
        state: true 
      sequence:
      - service: script.humidity_living_normal_message
