## HUMIDITY
- alias: 'humidity'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.humidity'
    attribute: 'average'
  action:
  - service: script.humidity_message
