## OCCUPANCY
### KITCHEN
- alias: 'occupancy_kitchen_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'kitchen'
    from: false
    to: true
  action:
  - service: script.occupancy_kitchen_on
  - service: script.occupancy_kitchen_message

- alias: 'occupancy_kitchen_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'kitchen'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'occupation') }}"
  action:
  - service: script.occupancy_kitchen_off
  - service: script.occupancy_kitchen_message

### HALL
- alias: 'occupancy_hall_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'hall'
    from: false
    to: true
  action:
  - service: script.occupancy_hall_on
  - service: script.occupancy_hall_message

- alias: 'occupancy_hall_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'hall'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'occupation') }}"
  action:
  - service: script.occupancy_hall_off
  - service: script.occupancy_hall_message

### BATH
- alias: 'occupancy_bath_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'bath'
    from: false
    to: true
  action:
  - service: script.occupancy_bath_on
  - service: script.occupancy_bath_message

- alias: 'occupancy_bath_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'bath'
    from: true
    to: false
    for: "{{ state_attr('sensor.delay', 'occupation') }}"
  action:
  - service: script.occupancy_bath_off
  - service: script.occupancy_bath_message

### TOILET
- alias: 'occupancy_toilet_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'toilet'
    from: false
    to: true
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet'
    state: false
  action:
  - service: script.occupancy_toilet_timer_start

- alias: 'occupancy_toilet_timer_cancel'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'toilet'
    from: true
    to: false
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet'
    state: true
  - condition: state
    entity_id: 'timer.occupancy_toilet'
    state: 'active'
  action:
  - service: script.occupancy_toilet_timer_cancel

- alias: 'occupancy_toilet_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'toilet'
    from: false
    to: true
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet'
    state: false
  action:
  - service: script.occupancy_toilet_on
  - service: script.occupancy_toilet_message

- alias: 'occupancy_toilet_off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'toilet'
    from: true
    to: false
  condition:
  - condition: state
    entity_id: 'binary_sensor.occupancy'
    attribute: 'toilet'
    state: true
  - condition: state
    entity_id: 'timer.occupancy_toilet'
    state: 'idle'
  action:
  - service: script.occupancy_toilet_off
  - service: script.occupancy_toilet_message
