## PARAMETERS

## LIGHT
## TODO: установить уровень яркости освещения по сенсору
## TODO: установить температуру сета по сенсору
## TODO: установить цветовую гамму по сенсору

## CURTAIN
## TODO: установить уровень штор по сенсору

# - alias: 'set_c_level'
#   initial_state: true
#   mode: 'queued'
#   trigger:
#   - platform: homeassistant
#     event: start
#   - platform: state
#     entity_id: 'sensor.c_level'
#   action:
#   - service: script.set_c_level