## PRESSURE
- alias: 'pressure'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.pressure'
    attribute: 'average'
  action:
  - service: script.pressure_message
  