## PROBLEM
### NETWORK
- alias: 'network'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.problem_network'
    attribute: 'download'
  - platform: state
    entity_id: 'sensor.problem_network'
    attribute: 'upload'
  - platform: state
    entity_id: 'sensor.problem_network'
    attribute: 'ping'
  action:
  - service: script.network_message

### HUMIDIFIER_EMPTY HALL
- alias: 'problem_empty_hall'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.problem_empty'
    attribute: 'problem_empty_hall'
    state: true
    # for: "{{ state_attr('sensor.delay', 'power') }}"
  action:
  - service: script.problem_empty_hall_low_message
      
### HUMIDIFIER_EMPTY BEDROOM
- alias: 'problem_empty_bedroom'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.problem_empty'
    attribute: 'problem_empty_bedroom'
    state: true
    # for: "{{ state_attr('sensor.delay', 'power') }}"
  action:
  - service: script.problem_empty_bedroom_low_message

### HUMIDIFIER_EMPTY LIVING
- alias: 'problem_empty_living'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.problem_empty'
    attribute: 'problem_empty_living'
    state: true
    # for: "{{ state_attr('sensor.delay', 'power') }}"
  action:
  - service: script.problem_empty_living_low_message
