## SOLAR
### AZIMUTH
- alias: 'solar_azimuth'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.solar'
    attribute: 'solar_azimuth'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.solar
        attribute: 'solar_azimuth'
        state: true
      sequence:
      - service: script.solar_azimuth_on_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.solar
        attribute: 'solar_azimuth'
        state: false
      sequence:
      - service: script.solar_azimuth_off_message

### ELEVATION
- alias: 'solar_elevation'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.solar'
    attribute: 'solar_elevation'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.solar
        attribute: 'solar_elevation'
        state: true
      sequence:
      - service: script.solar_elevation_on_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.solar
        attribute: 'solar_elevation'
        state: false
      sequence:
      - service: script.solar_elevation_off_message

### HIGHT
- alias: 'solar_hight'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: 'binary_sensor.solar'
    attribute: 'solar_hight'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.solar
        attribute: 'solar_hight'
        state: true
      sequence:
      - service: script.solar_hight_on_message
    - conditions:
      - condition: state
        entity_id: binary_sensor.solar
        attribute: 'solar_hight'
        state: false
      sequence:
      - service: script.solar_hight_off_message
