## STATUS
### SUSTEM
- alias: 'illuminance_kitchen_curtain'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: script.start_message

### DOOR
- alias: 'door_message'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'toilet'
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'hall'
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'bedroom'
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'living'
  - platform: state
    entity_id: 'binary_sensor.status_door'
    attribute: 'balcony'
  action:
  - service: script.door_message

### WINDOW
- alias: 'window_message'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.status_window'
    attribute: 'kitchen_left'
  - platform: state
    entity_id: 'binary_sensor.status_window'
    attribute: 'kitchen_right'
  - platform: state
    entity_id: 'binary_sensor.status_window'
    attribute: 'bedroom_left'
  - platform: state
    entity_id: 'binary_sensor.status_window'
    attribute: 'bedroom_right'
  - platform: state
    entity_id: 'binary_sensor.status_window'
    attribute: 'living'
  action:
  - service: script.window_message

## CURTAINS
- alias: 'status_curtain'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.status_curtain'
    attribute: 'kitchen'
  - platform: state
    entity_id: 'sensor.status_curtain'
    attribute: 'bedroom'
  - platform: state
    entity_id: 'sensor.status_curtain'
    attribute: 'living'
  action:
  - service: script.curtain_message
  
## PARTY_LIGHT
## TODO: отправить сообщение о новом статусе устройств

## TOP_LIGHT
## TODO: отправить сообщение о новом статусе устройств

## BACK_LIGHT
## TODO: отправить сообщение о новом статусе устройств

## NIGHT_LIGHT
## TODO: отправить сообщение о новом статусе устройств

## SWITCH
## TODO: отправить сообщение о новом статусе устройства

## DEHUMIDIFIER
## TODO: отправить сообщение о новом статусе устройства

## HUMIDIFIER
## TODO: отправить сообщение о новом статусе устройства
