## TEMPERATURE
- alias: 'temperature'
  initial_state: true
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'sensor.temperature'
    attribute: 'average'
  action:
  - service: script.temperature_message
