- platform: sql
  db_url: sqlite:////config/home-assistant_v2.db
  queries:

  - name: 't_kitchen_last'
    unit_of_measurement: '°C'
    icon: 'mdi:clipboard-text-clock-outline'
    query: "SELECT * FROM states WHERE entity_id = 'sensor.t_kitchen' AND state != 'unknown' ORDER BY state_id DESC LIMIT 1"
    column: 'state'

  - name: 't_hall_last'
    unit_of_measurement: '°C'
    icon: 'mdi:clipboard-text-clock-outline'
    query: "SELECT * FROM states WHERE entity_id = 'sensor.t_hall' AND state != 'unknown' ORDER BY state_id DESC LIMIT 1"
    column: 'state'

  - name: 't_bath_last'
    unit_of_measurement: '°C'
    icon: 'mdi:clipboard-text-clock-outline'
    query: "SELECT * FROM states WHERE entity_id = 'sensor.t_bath' AND state != 'unknown' ORDER BY state_id DESC LIMIT 1"
    column: 'state'

  - name: 't_bedroom_last'
    unit_of_measurement: '°C'
    icon: 'mdi:clipboard-text-clock-outline'
    query: "SELECT * FROM states WHERE entity_id = 'sensor.t_bedroom' AND state != 'unknown' ORDER BY state_id DESC LIMIT 1"
    column: 'state'

  - name: 't_living_last'
    unit_of_measurement: '°C'
    icon: 'mdi:clipboard-text-clock-outline'
    query: "SELECT * FROM states WHERE entity_id = 'sensor.t_living' AND state != 'unknown' ORDER BY state_id DESC LIMIT 1"
    column: 'state'

  - name: 't_balcony_last'
    unit_of_measurement: '°C'
    icon: 'mdi:clipboard-text-clock-outline'
    query: "SELECT * FROM states WHERE entity_id = 'sensor.t_balcony' AND state != 'unknown' ORDER BY state_id DESC LIMIT 1"
    column: 'state'
