## NAVIGATION BALCONY
- alias: message_navigation_balcony'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony'
  action:
  - service: script.message_navigation_balcony

## NAVIGATION BALCONY CLIMAT
- alias: message_navigation_balcony_climat'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony_climat'
  action:
  - service: script.message_navigation_balcony_climat

## NAVIGATION BALCONY SUN
- alias: message_navigation_balcony_sun'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony_sun'
  action:
  - service: script.message_navigation_balcony_sun

## NAVIGATION BALCONY LIGHT
- alias: message_navigation_balcony_light'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony_light'
  action:
  - service: script.message_navigation_balcony_light

## NAVIGATION BALCONY RELAY
- alias: message_navigation_balcony_relay'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony_relay'
  action:
  - service: script.message_navigation_balcony_relay

## NAVIGATION BALCONY SECURITY
- alias: message_navigation_balcony_security'
  mode: 'queued'
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data:
      command: '/balcony_security'
  action:
  - service: script.message_navigation_balcony_security

## MESSAGE BALCONY DOOR OPEN
- alias: 'message_door_balcony'
  mode: 'queued'
  trigger:
  - platform: state
    entity_id: 'binary_sensor.door_balcony_open'
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: 'binary_sensor.door_balcony_open'
    from: 'on'
    to: 'off'
  action:
  - service: script.message_door_balcony